/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32L4XX_HAL_H
#define _MOCK_STM32L4XX_HAL_H

#include "unity.h"
#include "stm32l4xx_hal.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_stm32l4xx_hal_Init(void);
void mock_stm32l4xx_hal_Destroy(void);
void mock_stm32l4xx_hal_Verify(void);




#define HAL_GPIO_WritePin_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _Ignore (not AndReturn)");
#define HAL_GPIO_WritePin_Ignore() HAL_GPIO_WritePin_CMockIgnore()
void HAL_GPIO_WritePin_CMockIgnore(void);
#define HAL_GPIO_WritePin_StopIgnore() HAL_GPIO_WritePin_CMockStopIgnore()
void HAL_GPIO_WritePin_CMockStopIgnore(void);
#define HAL_GPIO_WritePin_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _ExpectAnyArgs (not AndReturn)");
#define HAL_GPIO_WritePin_ExpectAnyArgs() HAL_GPIO_WritePin_CMockExpectAnyArgs(__LINE__)
void HAL_GPIO_WritePin_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_ExpectAndReturn(GPIOx, GPIO_Pin, PinState, cmock_retval) TEST_FAIL_MESSAGE("HAL_GPIO_WritePin requires _Expect (not AndReturn)");
#define HAL_GPIO_WritePin_Expect(GPIOx, GPIO_Pin, PinState) HAL_GPIO_WritePin_CMockExpect(__LINE__, GPIOx, GPIO_Pin, PinState)
void HAL_GPIO_WritePin_CMockExpect(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState);
typedef void (* CMOCK_HAL_GPIO_WritePin_CALLBACK)(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState, int cmock_num_calls);
void HAL_GPIO_WritePin_AddCallback(CMOCK_HAL_GPIO_WritePin_CALLBACK Callback);
void HAL_GPIO_WritePin_Stub(CMOCK_HAL_GPIO_WritePin_CALLBACK Callback);
#define HAL_GPIO_WritePin_StubWithCallback HAL_GPIO_WritePin_Stub
int HAL_GPIO_WritePin_CallCount(void);
#define HAL_GPIO_WritePin_ReturnThruPtr_GPIOx(GPIOx) HAL_GPIO_WritePin_CMockReturnMemThruPtr_GPIOx(__LINE__, GPIOx, sizeof(GPIO_TypeDef))
#define HAL_GPIO_WritePin_ReturnArrayThruPtr_GPIOx(GPIOx, cmock_len) HAL_GPIO_WritePin_CMockReturnMemThruPtr_GPIOx(__LINE__, GPIOx, (cmock_len * sizeof(*GPIOx)))
#define HAL_GPIO_WritePin_ReturnMemThruPtr_GPIOx(GPIOx, cmock_size) HAL_GPIO_WritePin_CMockReturnMemThruPtr_GPIOx(__LINE__, GPIOx, (cmock_size))
void HAL_GPIO_WritePin_CMockReturnMemThruPtr_GPIOx(UNITY_LINE_TYPE cmock_line, GPIO_TypeDef const* GPIOx, size_t cmock_size);
#define HAL_GPIO_WritePin_IgnoreArg_GPIOx() HAL_GPIO_WritePin_CMockIgnoreArg_GPIOx(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_GPIOx(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_IgnoreArg_GPIO_Pin() HAL_GPIO_WritePin_CMockIgnoreArg_GPIO_Pin(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_GPIO_Pin(UNITY_LINE_TYPE cmock_line);
#define HAL_GPIO_WritePin_IgnoreArg_PinState() HAL_GPIO_WritePin_CMockIgnoreArg_PinState(__LINE__)
void HAL_GPIO_WritePin_CMockIgnoreArg_PinState(UNITY_LINE_TYPE cmock_line);
#define HAL_GetTick_Ignore() TEST_FAIL_MESSAGE("HAL_GetTick requires _IgnoreAndReturn");
#define HAL_GetTick_IgnoreAndReturn(cmock_retval) HAL_GetTick_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_GetTick_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_GetTick_StopIgnore() HAL_GetTick_CMockStopIgnore()
void HAL_GetTick_CMockStopIgnore(void);
#define HAL_GetTick_Expect() TEST_FAIL_MESSAGE("HAL_GetTick requires _ExpectAndReturn");
#define HAL_GetTick_ExpectAndReturn(cmock_retval) HAL_GetTick_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_GetTick_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_HAL_GetTick_CALLBACK)(int cmock_num_calls);
void HAL_GetTick_AddCallback(CMOCK_HAL_GetTick_CALLBACK Callback);
void HAL_GetTick_Stub(CMOCK_HAL_GetTick_CALLBACK Callback);
#define HAL_GetTick_StubWithCallback HAL_GetTick_Stub
int HAL_GetTick_CallCount(void);
#define HAL_Delay_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_Delay requires _Ignore (not AndReturn)");
#define HAL_Delay_Ignore() HAL_Delay_CMockIgnore()
void HAL_Delay_CMockIgnore(void);
#define HAL_Delay_StopIgnore() HAL_Delay_CMockStopIgnore()
void HAL_Delay_CMockStopIgnore(void);
#define HAL_Delay_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_Delay requires _ExpectAnyArgs (not AndReturn)");
#define HAL_Delay_ExpectAnyArgs() HAL_Delay_CMockExpectAnyArgs(__LINE__)
void HAL_Delay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define HAL_Delay_ExpectAndReturn(Delay, cmock_retval) TEST_FAIL_MESSAGE("HAL_Delay requires _Expect (not AndReturn)");
#define HAL_Delay_Expect(Delay) HAL_Delay_CMockExpect(__LINE__, Delay)
void HAL_Delay_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Delay);
typedef void (* CMOCK_HAL_Delay_CALLBACK)(uint32_t Delay, int cmock_num_calls);
void HAL_Delay_AddCallback(CMOCK_HAL_Delay_CALLBACK Callback);
void HAL_Delay_Stub(CMOCK_HAL_Delay_CALLBACK Callback);
#define HAL_Delay_StubWithCallback HAL_Delay_Stub
int HAL_Delay_CallCount(void);
#define HAL_Delay_IgnoreArg_Delay() HAL_Delay_CMockIgnoreArg_Delay(__LINE__)
void HAL_Delay_CMockIgnoreArg_Delay(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _IgnoreAndReturn");
#define HAL_I2C_Mem_Read_IgnoreAndReturn(cmock_retval) HAL_I2C_Mem_Read_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_StopIgnore() HAL_I2C_Mem_Read_CMockStopIgnore()
void HAL_I2C_Mem_Read_CMockStopIgnore(void);
#define HAL_I2C_Mem_Read_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Mem_Read_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Mem_Read_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_Expect(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_I2C_Mem_Read requires _ExpectAndReturn");
#define HAL_I2C_Mem_Read_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval) HAL_I2C_Mem_Read_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Mem_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Mem_Read_CALLBACK)(I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_I2C_Mem_Read_AddCallback(CMOCK_HAL_I2C_Mem_Read_CALLBACK Callback);
void HAL_I2C_Mem_Read_Stub(CMOCK_HAL_I2C_Mem_Read_CALLBACK Callback);
#define HAL_I2C_Mem_Read_StubWithCallback HAL_I2C_Mem_Read_Stub
int HAL_I2C_Mem_Read_CallCount(void);
#define HAL_I2C_Mem_Read_ReturnThruPtr_hi2c(hi2c) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, sizeof(I2C_HandleTypeDef))
#define HAL_I2C_Mem_Read_ReturnArrayThruPtr_hi2c(hi2c, cmock_len) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, (cmock_len * sizeof(*hi2c)))
#define HAL_I2C_Mem_Read_ReturnMemThruPtr_hi2c(hi2c, cmock_size) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, (cmock_size))
void HAL_I2C_Mem_Read_CMockReturnMemThruPtr_hi2c(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef const* hi2c, size_t cmock_size);
#define HAL_I2C_Mem_Read_ReturnThruPtr_pData(pData) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_pData(__LINE__, pData, sizeof(uint8_t))
#define HAL_I2C_Mem_Read_ReturnArrayThruPtr_pData(pData, cmock_len) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_pData(__LINE__, pData, (cmock_len * sizeof(*pData)))
#define HAL_I2C_Mem_Read_ReturnMemThruPtr_pData(pData, cmock_size) HAL_I2C_Mem_Read_CMockReturnMemThruPtr_pData(__LINE__, pData, (cmock_size))
void HAL_I2C_Mem_Read_CMockReturnMemThruPtr_pData(UNITY_LINE_TYPE cmock_line, uint8_t const* pData, size_t cmock_size);
#define HAL_I2C_Mem_Read_IgnoreArg_hi2c() HAL_I2C_Mem_Read_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_DevAddress() HAL_I2C_Mem_Read_CMockIgnoreArg_DevAddress(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_DevAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_MemAddress() HAL_I2C_Mem_Read_CMockIgnoreArg_MemAddress(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_MemAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_MemAddSize() HAL_I2C_Mem_Read_CMockIgnoreArg_MemAddSize(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_MemAddSize(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_pData() HAL_I2C_Mem_Read_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_Size() HAL_I2C_Mem_Read_CMockIgnoreArg_Size(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_Size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Read_IgnoreArg_Timeout() HAL_I2C_Mem_Read_CMockIgnoreArg_Timeout(__LINE__)
void HAL_I2C_Mem_Read_CMockIgnoreArg_Timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_Ignore() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _IgnoreAndReturn");
#define HAL_I2C_Mem_Write_IgnoreAndReturn(cmock_retval) HAL_I2C_Mem_Write_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Write_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_StopIgnore() HAL_I2C_Mem_Write_CMockStopIgnore()
void HAL_I2C_Mem_Write_CMockStopIgnore(void);
#define HAL_I2C_Mem_Write_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _ExpectAnyArgsAndReturn");
#define HAL_I2C_Mem_Write_ExpectAnyArgsAndReturn(cmock_retval) HAL_I2C_Mem_Write_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_I2C_Mem_Write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_Expect(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_I2C_Mem_Write requires _ExpectAndReturn");
#define HAL_I2C_Mem_Write_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval) HAL_I2C_Mem_Write_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Mem_Write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_I2C_Mem_Write_CALLBACK)(I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_I2C_Mem_Write_AddCallback(CMOCK_HAL_I2C_Mem_Write_CALLBACK Callback);
void HAL_I2C_Mem_Write_Stub(CMOCK_HAL_I2C_Mem_Write_CALLBACK Callback);
#define HAL_I2C_Mem_Write_StubWithCallback HAL_I2C_Mem_Write_Stub
int HAL_I2C_Mem_Write_CallCount(void);
#define HAL_I2C_Mem_Write_ReturnThruPtr_hi2c(hi2c) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, sizeof(I2C_HandleTypeDef))
#define HAL_I2C_Mem_Write_ReturnArrayThruPtr_hi2c(hi2c, cmock_len) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, (cmock_len * sizeof(*hi2c)))
#define HAL_I2C_Mem_Write_ReturnMemThruPtr_hi2c(hi2c, cmock_size) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_hi2c(__LINE__, hi2c, (cmock_size))
void HAL_I2C_Mem_Write_CMockReturnMemThruPtr_hi2c(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef const* hi2c, size_t cmock_size);
#define HAL_I2C_Mem_Write_ReturnThruPtr_pData(pData) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_pData(__LINE__, pData, sizeof(uint8_t))
#define HAL_I2C_Mem_Write_ReturnArrayThruPtr_pData(pData, cmock_len) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_pData(__LINE__, pData, (cmock_len * sizeof(*pData)))
#define HAL_I2C_Mem_Write_ReturnMemThruPtr_pData(pData, cmock_size) HAL_I2C_Mem_Write_CMockReturnMemThruPtr_pData(__LINE__, pData, (cmock_size))
void HAL_I2C_Mem_Write_CMockReturnMemThruPtr_pData(UNITY_LINE_TYPE cmock_line, uint8_t const* pData, size_t cmock_size);
#define HAL_I2C_Mem_Write_IgnoreArg_hi2c() HAL_I2C_Mem_Write_CMockIgnoreArg_hi2c(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_hi2c(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_DevAddress() HAL_I2C_Mem_Write_CMockIgnoreArg_DevAddress(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_DevAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_MemAddress() HAL_I2C_Mem_Write_CMockIgnoreArg_MemAddress(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_MemAddress(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_MemAddSize() HAL_I2C_Mem_Write_CMockIgnoreArg_MemAddSize(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_MemAddSize(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_pData() HAL_I2C_Mem_Write_CMockIgnoreArg_pData(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_pData(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_Size() HAL_I2C_Mem_Write_CMockIgnoreArg_Size(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_Size(UNITY_LINE_TYPE cmock_line);
#define HAL_I2C_Mem_Write_IgnoreArg_Timeout() HAL_I2C_Mem_Write_CMockIgnoreArg_Timeout(__LINE__)
void HAL_I2C_Mem_Write_CMockIgnoreArg_Timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_FLASH_Unlock_Ignore() TEST_FAIL_MESSAGE("HAL_FLASH_Unlock requires _IgnoreAndReturn");
#define HAL_FLASH_Unlock_IgnoreAndReturn(cmock_retval) HAL_FLASH_Unlock_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Unlock_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASH_Unlock_StopIgnore() HAL_FLASH_Unlock_CMockStopIgnore()
void HAL_FLASH_Unlock_CMockStopIgnore(void);
#define HAL_FLASH_Unlock_Expect() TEST_FAIL_MESSAGE("HAL_FLASH_Unlock requires _ExpectAndReturn");
#define HAL_FLASH_Unlock_ExpectAndReturn(cmock_retval) HAL_FLASH_Unlock_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Unlock_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_FLASH_Unlock_CALLBACK)(int cmock_num_calls);
void HAL_FLASH_Unlock_AddCallback(CMOCK_HAL_FLASH_Unlock_CALLBACK Callback);
void HAL_FLASH_Unlock_Stub(CMOCK_HAL_FLASH_Unlock_CALLBACK Callback);
#define HAL_FLASH_Unlock_StubWithCallback HAL_FLASH_Unlock_Stub
int HAL_FLASH_Unlock_CallCount(void);
#define HAL_FLASH_Lock_Ignore() TEST_FAIL_MESSAGE("HAL_FLASH_Lock requires _IgnoreAndReturn");
#define HAL_FLASH_Lock_IgnoreAndReturn(cmock_retval) HAL_FLASH_Lock_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Lock_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASH_Lock_StopIgnore() HAL_FLASH_Lock_CMockStopIgnore()
void HAL_FLASH_Lock_CMockStopIgnore(void);
#define HAL_FLASH_Lock_Expect() TEST_FAIL_MESSAGE("HAL_FLASH_Lock requires _ExpectAndReturn");
#define HAL_FLASH_Lock_ExpectAndReturn(cmock_retval) HAL_FLASH_Lock_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Lock_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_FLASH_Lock_CALLBACK)(int cmock_num_calls);
void HAL_FLASH_Lock_AddCallback(CMOCK_HAL_FLASH_Lock_CALLBACK Callback);
void HAL_FLASH_Lock_Stub(CMOCK_HAL_FLASH_Lock_CALLBACK Callback);
#define HAL_FLASH_Lock_StubWithCallback HAL_FLASH_Lock_Stub
int HAL_FLASH_Lock_CallCount(void);
#define HAL_FLASH_Program_Ignore() TEST_FAIL_MESSAGE("HAL_FLASH_Program requires _IgnoreAndReturn");
#define HAL_FLASH_Program_IgnoreAndReturn(cmock_retval) HAL_FLASH_Program_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Program_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASH_Program_StopIgnore() HAL_FLASH_Program_CMockStopIgnore()
void HAL_FLASH_Program_CMockStopIgnore(void);
#define HAL_FLASH_Program_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_FLASH_Program requires _ExpectAnyArgsAndReturn");
#define HAL_FLASH_Program_ExpectAnyArgsAndReturn(cmock_retval) HAL_FLASH_Program_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_FLASH_Program_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASH_Program_Expect(TypeProgram, Address, Data) TEST_FAIL_MESSAGE("HAL_FLASH_Program requires _ExpectAndReturn");
#define HAL_FLASH_Program_ExpectAndReturn(TypeProgram, Address, Data, cmock_retval) HAL_FLASH_Program_CMockExpectAndReturn(__LINE__, TypeProgram, Address, Data, cmock_retval)
void HAL_FLASH_Program_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t TypeProgram, uint32_t Address, uint64_t Data, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_FLASH_Program_CALLBACK)(uint32_t TypeProgram, uint32_t Address, uint64_t Data, int cmock_num_calls);
void HAL_FLASH_Program_AddCallback(CMOCK_HAL_FLASH_Program_CALLBACK Callback);
void HAL_FLASH_Program_Stub(CMOCK_HAL_FLASH_Program_CALLBACK Callback);
#define HAL_FLASH_Program_StubWithCallback HAL_FLASH_Program_Stub
int HAL_FLASH_Program_CallCount(void);
#define HAL_FLASH_Program_IgnoreArg_TypeProgram() HAL_FLASH_Program_CMockIgnoreArg_TypeProgram(__LINE__)
void HAL_FLASH_Program_CMockIgnoreArg_TypeProgram(UNITY_LINE_TYPE cmock_line);
#define HAL_FLASH_Program_IgnoreArg_Address() HAL_FLASH_Program_CMockIgnoreArg_Address(__LINE__)
void HAL_FLASH_Program_CMockIgnoreArg_Address(UNITY_LINE_TYPE cmock_line);
#define HAL_FLASH_Program_IgnoreArg_Data() HAL_FLASH_Program_CMockIgnoreArg_Data(__LINE__)
void HAL_FLASH_Program_CMockIgnoreArg_Data(UNITY_LINE_TYPE cmock_line);
#define HAL_FLASHEx_Erase_Ignore() TEST_FAIL_MESSAGE("HAL_FLASHEx_Erase requires _IgnoreAndReturn");
#define HAL_FLASHEx_Erase_IgnoreAndReturn(cmock_retval) HAL_FLASHEx_Erase_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_FLASHEx_Erase_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASHEx_Erase_StopIgnore() HAL_FLASHEx_Erase_CMockStopIgnore()
void HAL_FLASHEx_Erase_CMockStopIgnore(void);
#define HAL_FLASHEx_Erase_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_FLASHEx_Erase requires _ExpectAnyArgsAndReturn");
#define HAL_FLASHEx_Erase_ExpectAnyArgsAndReturn(cmock_retval) HAL_FLASHEx_Erase_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_FLASHEx_Erase_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_FLASHEx_Erase_Expect(pEraseInit, PageError) TEST_FAIL_MESSAGE("HAL_FLASHEx_Erase requires _ExpectAndReturn");
#define HAL_FLASHEx_Erase_ExpectAndReturn(pEraseInit, PageError, cmock_retval) HAL_FLASHEx_Erase_CMockExpectAndReturn(__LINE__, pEraseInit, PageError, cmock_retval)
void HAL_FLASHEx_Erase_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FLASH_EraseInitTypeDef* pEraseInit, uint32_t* PageError, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_FLASHEx_Erase_CALLBACK)(FLASH_EraseInitTypeDef* pEraseInit, uint32_t* PageError, int cmock_num_calls);
void HAL_FLASHEx_Erase_AddCallback(CMOCK_HAL_FLASHEx_Erase_CALLBACK Callback);
void HAL_FLASHEx_Erase_Stub(CMOCK_HAL_FLASHEx_Erase_CALLBACK Callback);
#define HAL_FLASHEx_Erase_StubWithCallback HAL_FLASHEx_Erase_Stub
int HAL_FLASHEx_Erase_CallCount(void);
#define HAL_FLASHEx_Erase_ReturnThruPtr_pEraseInit(pEraseInit) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_pEraseInit(__LINE__, pEraseInit, sizeof(FLASH_EraseInitTypeDef))
#define HAL_FLASHEx_Erase_ReturnArrayThruPtr_pEraseInit(pEraseInit, cmock_len) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_pEraseInit(__LINE__, pEraseInit, (cmock_len * sizeof(*pEraseInit)))
#define HAL_FLASHEx_Erase_ReturnMemThruPtr_pEraseInit(pEraseInit, cmock_size) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_pEraseInit(__LINE__, pEraseInit, (cmock_size))
void HAL_FLASHEx_Erase_CMockReturnMemThruPtr_pEraseInit(UNITY_LINE_TYPE cmock_line, FLASH_EraseInitTypeDef const* pEraseInit, size_t cmock_size);
#define HAL_FLASHEx_Erase_ReturnThruPtr_PageError(PageError) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_PageError(__LINE__, PageError, sizeof(uint32_t))
#define HAL_FLASHEx_Erase_ReturnArrayThruPtr_PageError(PageError, cmock_len) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_PageError(__LINE__, PageError, (cmock_len * sizeof(*PageError)))
#define HAL_FLASHEx_Erase_ReturnMemThruPtr_PageError(PageError, cmock_size) HAL_FLASHEx_Erase_CMockReturnMemThruPtr_PageError(__LINE__, PageError, (cmock_size))
void HAL_FLASHEx_Erase_CMockReturnMemThruPtr_PageError(UNITY_LINE_TYPE cmock_line, uint32_t const* PageError, size_t cmock_size);
#define HAL_FLASHEx_Erase_IgnoreArg_pEraseInit() HAL_FLASHEx_Erase_CMockIgnoreArg_pEraseInit(__LINE__)
void HAL_FLASHEx_Erase_CMockIgnoreArg_pEraseInit(UNITY_LINE_TYPE cmock_line);
#define HAL_FLASHEx_Erase_IgnoreArg_PageError() HAL_FLASHEx_Erase_CMockIgnoreArg_PageError(__LINE__)
void HAL_FLASHEx_Erase_CMockIgnoreArg_PageError(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_Start_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_Start requires _IgnoreAndReturn");
#define HAL_ADC_Start_IgnoreAndReturn(cmock_retval) HAL_ADC_Start_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Start_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Start_StopIgnore() HAL_ADC_Start_CMockStopIgnore()
void HAL_ADC_Start_CMockStopIgnore(void);
#define HAL_ADC_Start_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_ADC_Start requires _ExpectAnyArgsAndReturn");
#define HAL_ADC_Start_ExpectAnyArgsAndReturn(cmock_retval) HAL_ADC_Start_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Start_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Start_Expect(hadc) TEST_FAIL_MESSAGE("HAL_ADC_Start requires _ExpectAndReturn");
#define HAL_ADC_Start_ExpectAndReturn(hadc, cmock_retval) HAL_ADC_Start_CMockExpectAndReturn(__LINE__, hadc, cmock_retval)
void HAL_ADC_Start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_ADC_Start_CALLBACK)(ADC_HandleTypeDef* hadc, int cmock_num_calls);
void HAL_ADC_Start_AddCallback(CMOCK_HAL_ADC_Start_CALLBACK Callback);
void HAL_ADC_Start_Stub(CMOCK_HAL_ADC_Start_CALLBACK Callback);
#define HAL_ADC_Start_StubWithCallback HAL_ADC_Start_Stub
int HAL_ADC_Start_CallCount(void);
#define HAL_ADC_Start_ReturnThruPtr_hadc(hadc) HAL_ADC_Start_CMockReturnMemThruPtr_hadc(__LINE__, hadc, sizeof(ADC_HandleTypeDef))
#define HAL_ADC_Start_ReturnArrayThruPtr_hadc(hadc, cmock_len) HAL_ADC_Start_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_len * sizeof(*hadc)))
#define HAL_ADC_Start_ReturnMemThruPtr_hadc(hadc, cmock_size) HAL_ADC_Start_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_size))
void HAL_ADC_Start_CMockReturnMemThruPtr_hadc(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef const* hadc, size_t cmock_size);
#define HAL_ADC_Start_IgnoreArg_hadc() HAL_ADC_Start_CMockIgnoreArg_hadc(__LINE__)
void HAL_ADC_Start_CMockIgnoreArg_hadc(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_Stop_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_Stop requires _IgnoreAndReturn");
#define HAL_ADC_Stop_IgnoreAndReturn(cmock_retval) HAL_ADC_Stop_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Stop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Stop_StopIgnore() HAL_ADC_Stop_CMockStopIgnore()
void HAL_ADC_Stop_CMockStopIgnore(void);
#define HAL_ADC_Stop_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_ADC_Stop requires _ExpectAnyArgsAndReturn");
#define HAL_ADC_Stop_ExpectAnyArgsAndReturn(cmock_retval) HAL_ADC_Stop_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_ADC_Stop_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_Stop_Expect(hadc) TEST_FAIL_MESSAGE("HAL_ADC_Stop requires _ExpectAndReturn");
#define HAL_ADC_Stop_ExpectAndReturn(hadc, cmock_retval) HAL_ADC_Stop_CMockExpectAndReturn(__LINE__, hadc, cmock_retval)
void HAL_ADC_Stop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_ADC_Stop_CALLBACK)(ADC_HandleTypeDef* hadc, int cmock_num_calls);
void HAL_ADC_Stop_AddCallback(CMOCK_HAL_ADC_Stop_CALLBACK Callback);
void HAL_ADC_Stop_Stub(CMOCK_HAL_ADC_Stop_CALLBACK Callback);
#define HAL_ADC_Stop_StubWithCallback HAL_ADC_Stop_Stub
int HAL_ADC_Stop_CallCount(void);
#define HAL_ADC_Stop_ReturnThruPtr_hadc(hadc) HAL_ADC_Stop_CMockReturnMemThruPtr_hadc(__LINE__, hadc, sizeof(ADC_HandleTypeDef))
#define HAL_ADC_Stop_ReturnArrayThruPtr_hadc(hadc, cmock_len) HAL_ADC_Stop_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_len * sizeof(*hadc)))
#define HAL_ADC_Stop_ReturnMemThruPtr_hadc(hadc, cmock_size) HAL_ADC_Stop_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_size))
void HAL_ADC_Stop_CMockReturnMemThruPtr_hadc(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef const* hadc, size_t cmock_size);
#define HAL_ADC_Stop_IgnoreArg_hadc() HAL_ADC_Stop_CMockIgnoreArg_hadc(__LINE__)
void HAL_ADC_Stop_CMockIgnoreArg_hadc(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_PollForConversion_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_PollForConversion requires _IgnoreAndReturn");
#define HAL_ADC_PollForConversion_IgnoreAndReturn(cmock_retval) HAL_ADC_PollForConversion_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_PollForConversion_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_PollForConversion_StopIgnore() HAL_ADC_PollForConversion_CMockStopIgnore()
void HAL_ADC_PollForConversion_CMockStopIgnore(void);
#define HAL_ADC_PollForConversion_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_ADC_PollForConversion requires _ExpectAnyArgsAndReturn");
#define HAL_ADC_PollForConversion_ExpectAnyArgsAndReturn(cmock_retval) HAL_ADC_PollForConversion_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_ADC_PollForConversion_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_ADC_PollForConversion_Expect(hadc, Timeout) TEST_FAIL_MESSAGE("HAL_ADC_PollForConversion requires _ExpectAndReturn");
#define HAL_ADC_PollForConversion_ExpectAndReturn(hadc, Timeout, cmock_retval) HAL_ADC_PollForConversion_CMockExpectAndReturn(__LINE__, hadc, Timeout, cmock_retval)
void HAL_ADC_PollForConversion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_ADC_PollForConversion_CALLBACK)(ADC_HandleTypeDef* hadc, uint32_t Timeout, int cmock_num_calls);
void HAL_ADC_PollForConversion_AddCallback(CMOCK_HAL_ADC_PollForConversion_CALLBACK Callback);
void HAL_ADC_PollForConversion_Stub(CMOCK_HAL_ADC_PollForConversion_CALLBACK Callback);
#define HAL_ADC_PollForConversion_StubWithCallback HAL_ADC_PollForConversion_Stub
int HAL_ADC_PollForConversion_CallCount(void);
#define HAL_ADC_PollForConversion_ReturnThruPtr_hadc(hadc) HAL_ADC_PollForConversion_CMockReturnMemThruPtr_hadc(__LINE__, hadc, sizeof(ADC_HandleTypeDef))
#define HAL_ADC_PollForConversion_ReturnArrayThruPtr_hadc(hadc, cmock_len) HAL_ADC_PollForConversion_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_len * sizeof(*hadc)))
#define HAL_ADC_PollForConversion_ReturnMemThruPtr_hadc(hadc, cmock_size) HAL_ADC_PollForConversion_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_size))
void HAL_ADC_PollForConversion_CMockReturnMemThruPtr_hadc(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef const* hadc, size_t cmock_size);
#define HAL_ADC_PollForConversion_IgnoreArg_hadc() HAL_ADC_PollForConversion_CMockIgnoreArg_hadc(__LINE__)
void HAL_ADC_PollForConversion_CMockIgnoreArg_hadc(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_PollForConversion_IgnoreArg_Timeout() HAL_ADC_PollForConversion_CMockIgnoreArg_Timeout(__LINE__)
void HAL_ADC_PollForConversion_CMockIgnoreArg_Timeout(UNITY_LINE_TYPE cmock_line);
#define HAL_ADC_GetValue_Ignore() TEST_FAIL_MESSAGE("HAL_ADC_GetValue requires _IgnoreAndReturn");
#define HAL_ADC_GetValue_IgnoreAndReturn(cmock_retval) HAL_ADC_GetValue_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_ADC_GetValue_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_ADC_GetValue_StopIgnore() HAL_ADC_GetValue_CMockStopIgnore()
void HAL_ADC_GetValue_CMockStopIgnore(void);
#define HAL_ADC_GetValue_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_ADC_GetValue requires _ExpectAnyArgsAndReturn");
#define HAL_ADC_GetValue_ExpectAnyArgsAndReturn(cmock_retval) HAL_ADC_GetValue_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_ADC_GetValue_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_ADC_GetValue_Expect(hadc) TEST_FAIL_MESSAGE("HAL_ADC_GetValue requires _ExpectAndReturn");
#define HAL_ADC_GetValue_ExpectAndReturn(hadc, cmock_retval) HAL_ADC_GetValue_CMockExpectAndReturn(__LINE__, hadc, cmock_retval)
void HAL_ADC_GetValue_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef* hadc, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_HAL_ADC_GetValue_CALLBACK)(ADC_HandleTypeDef* hadc, int cmock_num_calls);
void HAL_ADC_GetValue_AddCallback(CMOCK_HAL_ADC_GetValue_CALLBACK Callback);
void HAL_ADC_GetValue_Stub(CMOCK_HAL_ADC_GetValue_CALLBACK Callback);
#define HAL_ADC_GetValue_StubWithCallback HAL_ADC_GetValue_Stub
int HAL_ADC_GetValue_CallCount(void);
#define HAL_ADC_GetValue_ReturnThruPtr_hadc(hadc) HAL_ADC_GetValue_CMockReturnMemThruPtr_hadc(__LINE__, hadc, sizeof(ADC_HandleTypeDef))
#define HAL_ADC_GetValue_ReturnArrayThruPtr_hadc(hadc, cmock_len) HAL_ADC_GetValue_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_len * sizeof(*hadc)))
#define HAL_ADC_GetValue_ReturnMemThruPtr_hadc(hadc, cmock_size) HAL_ADC_GetValue_CMockReturnMemThruPtr_hadc(__LINE__, hadc, (cmock_size))
void HAL_ADC_GetValue_CMockReturnMemThruPtr_hadc(UNITY_LINE_TYPE cmock_line, ADC_HandleTypeDef const* hadc, size_t cmock_size);
#define HAL_ADC_GetValue_IgnoreArg_hadc() HAL_ADC_GetValue_CMockIgnoreArg_hadc(__LINE__)
void HAL_ADC_GetValue_CMockIgnoreArg_hadc(UNITY_LINE_TYPE cmock_line);
#define HAL_IWDG_Refresh_Ignore() TEST_FAIL_MESSAGE("HAL_IWDG_Refresh requires _IgnoreAndReturn");
#define HAL_IWDG_Refresh_IgnoreAndReturn(cmock_retval) HAL_IWDG_Refresh_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_IWDG_Refresh_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_IWDG_Refresh_StopIgnore() HAL_IWDG_Refresh_CMockStopIgnore()
void HAL_IWDG_Refresh_CMockStopIgnore(void);
#define HAL_IWDG_Refresh_ExpectAnyArgs() TEST_FAIL_MESSAGE("HAL_IWDG_Refresh requires _ExpectAnyArgsAndReturn");
#define HAL_IWDG_Refresh_ExpectAnyArgsAndReturn(cmock_retval) HAL_IWDG_Refresh_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void HAL_IWDG_Refresh_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_IWDG_Refresh_Expect(hiwdg) TEST_FAIL_MESSAGE("HAL_IWDG_Refresh requires _ExpectAndReturn");
#define HAL_IWDG_Refresh_ExpectAndReturn(hiwdg, cmock_retval) HAL_IWDG_Refresh_CMockExpectAndReturn(__LINE__, hiwdg, cmock_retval)
void HAL_IWDG_Refresh_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, IWDG_HandleTypeDef* hiwdg, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_IWDG_Refresh_CALLBACK)(IWDG_HandleTypeDef* hiwdg, int cmock_num_calls);
void HAL_IWDG_Refresh_AddCallback(CMOCK_HAL_IWDG_Refresh_CALLBACK Callback);
void HAL_IWDG_Refresh_Stub(CMOCK_HAL_IWDG_Refresh_CALLBACK Callback);
#define HAL_IWDG_Refresh_StubWithCallback HAL_IWDG_Refresh_Stub
int HAL_IWDG_Refresh_CallCount(void);
#define HAL_IWDG_Refresh_ReturnThruPtr_hiwdg(hiwdg) HAL_IWDG_Refresh_CMockReturnMemThruPtr_hiwdg(__LINE__, hiwdg, sizeof(IWDG_HandleTypeDef))
#define HAL_IWDG_Refresh_ReturnArrayThruPtr_hiwdg(hiwdg, cmock_len) HAL_IWDG_Refresh_CMockReturnMemThruPtr_hiwdg(__LINE__, hiwdg, (cmock_len * sizeof(*hiwdg)))
#define HAL_IWDG_Refresh_ReturnMemThruPtr_hiwdg(hiwdg, cmock_size) HAL_IWDG_Refresh_CMockReturnMemThruPtr_hiwdg(__LINE__, hiwdg, (cmock_size))
void HAL_IWDG_Refresh_CMockReturnMemThruPtr_hiwdg(UNITY_LINE_TYPE cmock_line, IWDG_HandleTypeDef const* hiwdg, size_t cmock_size);
#define HAL_IWDG_Refresh_IgnoreArg_hiwdg() HAL_IWDG_Refresh_CMockIgnoreArg_hiwdg(__LINE__)
void HAL_IWDG_Refresh_CMockIgnoreArg_hiwdg(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
