/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_task.h"

static const char* CMockString_vTaskDelay = "vTaskDelay";
static const char* CMockString_xTaskGetCurrentTaskHandle = "xTaskGetCurrentTaskHandle";
static const char* CMockString_xTaskGetTickCount = "xTaskGetTickCount";
static const char* CMockString_xTicksToDelay = "xTicksToDelay";

typedef struct _CMOCK_xTaskGetTickCount_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  TickType_t ReturnVal;

} CMOCK_xTaskGetTickCount_CALL_INSTANCE;

typedef struct _CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  TaskHandle_t ReturnVal;

} CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE;

typedef struct _CMOCK_vTaskDelay_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  TickType_t Expected_xTicksToDelay;
  char IgnoreArg_xTicksToDelay;

} CMOCK_vTaskDelay_CALL_INSTANCE;

static struct mock_taskInstance
{
  char xTaskGetTickCount_IgnoreBool;
  TickType_t xTaskGetTickCount_FinalReturn;
  char xTaskGetTickCount_CallbackBool;
  CMOCK_xTaskGetTickCount_CALLBACK xTaskGetTickCount_CallbackFunctionPointer;
  int xTaskGetTickCount_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xTaskGetTickCount_CallInstance;
  char xTaskGetCurrentTaskHandle_IgnoreBool;
  TaskHandle_t xTaskGetCurrentTaskHandle_FinalReturn;
  char xTaskGetCurrentTaskHandle_CallbackBool;
  CMOCK_xTaskGetCurrentTaskHandle_CALLBACK xTaskGetCurrentTaskHandle_CallbackFunctionPointer;
  int xTaskGetCurrentTaskHandle_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE xTaskGetCurrentTaskHandle_CallInstance;
  char vTaskDelay_IgnoreBool;
  char vTaskDelay_CallbackBool;
  CMOCK_vTaskDelay_CALLBACK vTaskDelay_CallbackFunctionPointer;
  int vTaskDelay_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE vTaskDelay_CallInstance;
} Mock;


void mock_task_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.xTaskGetTickCount_CallInstance;
  if (Mock.xTaskGetTickCount_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xTaskGetTickCount);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xTaskGetTickCount_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.xTaskGetCurrentTaskHandle_CallInstance;
  if (Mock.xTaskGetCurrentTaskHandle_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_xTaskGetCurrentTaskHandle);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.vTaskDelay_CallInstance;
  if (Mock.vTaskDelay_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vTaskDelay);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.vTaskDelay_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_task_Init(void)
{
  mock_task_Destroy();
}

void mock_task_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

TickType_t xTaskGetTickCount(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xTaskGetTickCount_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xTaskGetTickCount);
  cmock_call_instance = (CMOCK_xTaskGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xTaskGetTickCount_CallInstance);
  Mock.xTaskGetTickCount_CallInstance = CMock_Guts_MemNext(Mock.xTaskGetTickCount_CallInstance);
  if (Mock.xTaskGetTickCount_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xTaskGetTickCount_FinalReturn;
    Mock.xTaskGetTickCount_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xTaskGetTickCount_CallbackBool &&
      Mock.xTaskGetTickCount_CallbackFunctionPointer != NULL)
  {
    TickType_t cmock_cb_ret = Mock.xTaskGetTickCount_CallbackFunctionPointer(Mock.xTaskGetTickCount_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.xTaskGetTickCount_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xTaskGetTickCount);
    cmock_call_instance->ReturnVal = Mock.xTaskGetTickCount_CallbackFunctionPointer(Mock.xTaskGetTickCount_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xTaskGetTickCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TickType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xTaskGetTickCount_CALL_INSTANCE));
  CMOCK_xTaskGetTickCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_xTaskGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xTaskGetTickCount_CallInstance = CMock_Guts_MemChain(Mock.xTaskGetTickCount_CallInstance, cmock_guts_index);
  Mock.xTaskGetTickCount_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xTaskGetTickCount_IgnoreBool = (char)1;
}

void xTaskGetTickCount_CMockStopIgnore(void)
{
  if(Mock.xTaskGetTickCount_IgnoreBool)
    Mock.xTaskGetTickCount_CallInstance = CMock_Guts_MemNext(Mock.xTaskGetTickCount_CallInstance);
  Mock.xTaskGetTickCount_IgnoreBool = (char)0;
}

void xTaskGetTickCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TickType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xTaskGetTickCount_CALL_INSTANCE));
  CMOCK_xTaskGetTickCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_xTaskGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xTaskGetTickCount_CallInstance = CMock_Guts_MemChain(Mock.xTaskGetTickCount_CallInstance, cmock_guts_index);
  Mock.xTaskGetTickCount_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void xTaskGetTickCount_AddCallback(CMOCK_xTaskGetTickCount_CALLBACK Callback)
{
  Mock.xTaskGetTickCount_IgnoreBool = (char)0;
  Mock.xTaskGetTickCount_CallbackBool = (char)1;
  Mock.xTaskGetTickCount_CallbackCalls = 0;
  Mock.xTaskGetTickCount_CallbackFunctionPointer = Callback;
}

int xTaskGetTickCount_CallCount(void)
{
  return Mock.xTaskGetTickCount_CallbackCalls;
}

void xTaskGetTickCount_Stub(CMOCK_xTaskGetTickCount_CALLBACK Callback)
{
  Mock.xTaskGetTickCount_IgnoreBool = (char)0;
  Mock.xTaskGetTickCount_CallbackBool = (char)0;
  Mock.xTaskGetTickCount_CallbackCalls = 0;
  Mock.xTaskGetTickCount_CallbackFunctionPointer = Callback;
}

TaskHandle_t xTaskGetCurrentTaskHandle(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_xTaskGetCurrentTaskHandle);
  cmock_call_instance = (CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.xTaskGetCurrentTaskHandle_CallInstance);
  Mock.xTaskGetCurrentTaskHandle_CallInstance = CMock_Guts_MemNext(Mock.xTaskGetCurrentTaskHandle_CallInstance);
  if (Mock.xTaskGetCurrentTaskHandle_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.xTaskGetCurrentTaskHandle_FinalReturn;
    memcpy((void*)(&Mock.xTaskGetCurrentTaskHandle_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(TaskHandle_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(TaskHandle_t) ? 1 : -1])); /* add TaskHandle_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.xTaskGetCurrentTaskHandle_CallbackBool &&
      Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer != NULL)
  {
    TaskHandle_t cmock_cb_ret = Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer(Mock.xTaskGetCurrentTaskHandle_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_xTaskGetCurrentTaskHandle);
    cmock_call_instance->ReturnVal = Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer(Mock.xTaskGetCurrentTaskHandle_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void xTaskGetCurrentTaskHandle_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE));
  CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE* cmock_call_instance = (CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xTaskGetCurrentTaskHandle_CallInstance = CMock_Guts_MemChain(Mock.xTaskGetCurrentTaskHandle_CallInstance, cmock_guts_index);
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)1;
}

void xTaskGetCurrentTaskHandle_CMockStopIgnore(void)
{
  if(Mock.xTaskGetCurrentTaskHandle_IgnoreBool)
    Mock.xTaskGetCurrentTaskHandle_CallInstance = CMock_Guts_MemNext(Mock.xTaskGetCurrentTaskHandle_CallInstance);
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)0;
}

void xTaskGetCurrentTaskHandle_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE));
  CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE* cmock_call_instance = (CMOCK_xTaskGetCurrentTaskHandle_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.xTaskGetCurrentTaskHandle_CallInstance = CMock_Guts_MemChain(Mock.xTaskGetCurrentTaskHandle_CallInstance, cmock_guts_index);
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(TaskHandle_t[sizeof(cmock_to_return) == sizeof(TaskHandle_t) ? 1 : -1])); /* add TaskHandle_t to :treat_as_array if this causes an error */
}

void xTaskGetCurrentTaskHandle_AddCallback(CMOCK_xTaskGetCurrentTaskHandle_CALLBACK Callback)
{
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)0;
  Mock.xTaskGetCurrentTaskHandle_CallbackBool = (char)1;
  Mock.xTaskGetCurrentTaskHandle_CallbackCalls = 0;
  Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer = Callback;
}

int xTaskGetCurrentTaskHandle_CallCount(void)
{
  return Mock.xTaskGetCurrentTaskHandle_CallbackCalls;
}

void xTaskGetCurrentTaskHandle_Stub(CMOCK_xTaskGetCurrentTaskHandle_CALLBACK Callback)
{
  Mock.xTaskGetCurrentTaskHandle_IgnoreBool = (char)0;
  Mock.xTaskGetCurrentTaskHandle_CallbackBool = (char)0;
  Mock.xTaskGetCurrentTaskHandle_CallbackCalls = 0;
  Mock.xTaskGetCurrentTaskHandle_CallbackFunctionPointer = Callback;
}

void vTaskDelay(TickType_t xTicksToDelay)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vTaskDelay);
  cmock_call_instance = (CMOCK_vTaskDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vTaskDelay_CallInstance);
  Mock.vTaskDelay_CallInstance = CMock_Guts_MemNext(Mock.vTaskDelay_CallInstance);
  if (Mock.vTaskDelay_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.vTaskDelay_CallbackBool &&
      Mock.vTaskDelay_CallbackFunctionPointer != NULL)
  {
    Mock.vTaskDelay_CallbackFunctionPointer(xTicksToDelay, Mock.vTaskDelay_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_xTicksToDelay)
  {
    UNITY_SET_DETAILS(CMockString_vTaskDelay,CMockString_xTicksToDelay);
    UNITY_TEST_ASSERT_EQUAL_UINT32(cmock_call_instance->Expected_xTicksToDelay, xTicksToDelay, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.vTaskDelay_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_vTaskDelay);
    Mock.vTaskDelay_CallbackFunctionPointer(xTicksToDelay, Mock.vTaskDelay_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vTaskDelay(CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance, TickType_t xTicksToDelay);
void CMockExpectParameters_vTaskDelay(CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance, TickType_t xTicksToDelay)
{
  cmock_call_instance->Expected_xTicksToDelay = xTicksToDelay;
  cmock_call_instance->IgnoreArg_xTicksToDelay = 0;
}

void vTaskDelay_CMockIgnore(void)
{
  Mock.vTaskDelay_IgnoreBool = (char)1;
}

void vTaskDelay_CMockStopIgnore(void)
{
  Mock.vTaskDelay_IgnoreBool = (char)0;
}

void vTaskDelay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vTaskDelay_CALL_INSTANCE));
  CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_vTaskDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vTaskDelay_CallInstance = CMock_Guts_MemChain(Mock.vTaskDelay_CallInstance, cmock_guts_index);
  Mock.vTaskDelay_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void vTaskDelay_CMockExpect(UNITY_LINE_TYPE cmock_line, TickType_t xTicksToDelay)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vTaskDelay_CALL_INSTANCE));
  CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_vTaskDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vTaskDelay_CallInstance = CMock_Guts_MemChain(Mock.vTaskDelay_CallInstance, cmock_guts_index);
  Mock.vTaskDelay_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_vTaskDelay(cmock_call_instance, xTicksToDelay);
}

void vTaskDelay_AddCallback(CMOCK_vTaskDelay_CALLBACK Callback)
{
  Mock.vTaskDelay_IgnoreBool = (char)0;
  Mock.vTaskDelay_CallbackBool = (char)1;
  Mock.vTaskDelay_CallbackCalls = 0;
  Mock.vTaskDelay_CallbackFunctionPointer = Callback;
}

int vTaskDelay_CallCount(void)
{
  return Mock.vTaskDelay_CallbackCalls;
}

void vTaskDelay_Stub(CMOCK_vTaskDelay_CALLBACK Callback)
{
  Mock.vTaskDelay_IgnoreBool = (char)0;
  Mock.vTaskDelay_CallbackBool = (char)0;
  Mock.vTaskDelay_CallbackCalls = 0;
  Mock.vTaskDelay_CallbackFunctionPointer = Callback;
}

void vTaskDelay_CMockIgnoreArg_xTicksToDelay(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_vTaskDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_vTaskDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.vTaskDelay_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_xTicksToDelay = 1;
}

