/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CMSIS_OS_H
#define _MOCK_CMSIS_OS_H

#include "unity.h"
#include "cmsis_os.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_cmsis_os_Init(void);
void mock_cmsis_os_Destroy(void);
void mock_cmsis_os_Verify(void);




#define osKernelStart_Ignore() TEST_FAIL_MESSAGE("osKernelStart requires _IgnoreAndReturn");
#define osKernelStart_IgnoreAndReturn(cmock_retval) osKernelStart_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osKernelStart_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osKernelStart_StopIgnore() osKernelStart_CMockStopIgnore()
void osKernelStart_CMockStopIgnore(void);
#define osKernelStart_Expect() TEST_FAIL_MESSAGE("osKernelStart requires _ExpectAndReturn");
#define osKernelStart_ExpectAndReturn(cmock_retval) osKernelStart_CMockExpectAndReturn(__LINE__, cmock_retval)
void osKernelStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
typedef osStatus_t (* CMOCK_osKernelStart_CALLBACK)(int cmock_num_calls);
void osKernelStart_AddCallback(CMOCK_osKernelStart_CALLBACK Callback);
void osKernelStart_Stub(CMOCK_osKernelStart_CALLBACK Callback);
#define osKernelStart_StubWithCallback osKernelStart_Stub
int osKernelStart_CallCount(void);
#define osKernelGetTickCount_Ignore() TEST_FAIL_MESSAGE("osKernelGetTickCount requires _IgnoreAndReturn");
#define osKernelGetTickCount_IgnoreAndReturn(cmock_retval) osKernelGetTickCount_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osKernelGetTickCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define osKernelGetTickCount_StopIgnore() osKernelGetTickCount_CMockStopIgnore()
void osKernelGetTickCount_CMockStopIgnore(void);
#define osKernelGetTickCount_Expect() TEST_FAIL_MESSAGE("osKernelGetTickCount requires _ExpectAndReturn");
#define osKernelGetTickCount_ExpectAndReturn(cmock_retval) osKernelGetTickCount_CMockExpectAndReturn(__LINE__, cmock_retval)
void osKernelGetTickCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_osKernelGetTickCount_CALLBACK)(int cmock_num_calls);
void osKernelGetTickCount_AddCallback(CMOCK_osKernelGetTickCount_CALLBACK Callback);
void osKernelGetTickCount_Stub(CMOCK_osKernelGetTickCount_CALLBACK Callback);
#define osKernelGetTickCount_StubWithCallback osKernelGetTickCount_Stub
int osKernelGetTickCount_CallCount(void);
#define osThreadNew_Ignore() TEST_FAIL_MESSAGE("osThreadNew requires _IgnoreAndReturn");
#define osThreadNew_IgnoreAndReturn(cmock_retval) osThreadNew_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osThreadNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
#define osThreadNew_StopIgnore() osThreadNew_CMockStopIgnore()
void osThreadNew_CMockStopIgnore(void);
#define osThreadNew_ExpectAnyArgs() TEST_FAIL_MESSAGE("osThreadNew requires _ExpectAnyArgsAndReturn");
#define osThreadNew_ExpectAnyArgsAndReturn(cmock_retval) osThreadNew_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osThreadNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
#define osThreadNew_Expect(func, argument, attr) TEST_FAIL_MESSAGE("osThreadNew requires _ExpectAndReturn");
#define osThreadNew_ExpectAndReturn(func, argument, attr, cmock_retval) osThreadNew_CMockExpectAndReturn(__LINE__, func, argument, attr, cmock_retval)
void osThreadNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadFunc_t func, void* argument, const osThreadAttr_t* attr, osThreadId_t cmock_to_return);
typedef osThreadId_t (* CMOCK_osThreadNew_CALLBACK)(osThreadFunc_t func, void* argument, const osThreadAttr_t* attr, int cmock_num_calls);
void osThreadNew_AddCallback(CMOCK_osThreadNew_CALLBACK Callback);
void osThreadNew_Stub(CMOCK_osThreadNew_CALLBACK Callback);
#define osThreadNew_StubWithCallback osThreadNew_Stub
int osThreadNew_CallCount(void);
#define osThreadNew_ReturnThruPtr_argument(argument) osThreadNew_CMockReturnMemThruPtr_argument(__LINE__, argument, sizeof(*argument))
#define osThreadNew_ReturnArrayThruPtr_argument(argument, cmock_len) osThreadNew_CMockReturnMemThruPtr_argument(__LINE__, argument, (cmock_len * sizeof(*argument)))
#define osThreadNew_ReturnMemThruPtr_argument(argument, cmock_size) osThreadNew_CMockReturnMemThruPtr_argument(__LINE__, argument, (cmock_size))
void osThreadNew_CMockReturnMemThruPtr_argument(UNITY_LINE_TYPE cmock_line, void const* argument, size_t cmock_size);
#define osThreadNew_IgnoreArg_func() osThreadNew_CMockIgnoreArg_func(__LINE__)
void osThreadNew_CMockIgnoreArg_func(UNITY_LINE_TYPE cmock_line);
#define osThreadNew_IgnoreArg_argument() osThreadNew_CMockIgnoreArg_argument(__LINE__)
void osThreadNew_CMockIgnoreArg_argument(UNITY_LINE_TYPE cmock_line);
#define osThreadNew_IgnoreArg_attr() osThreadNew_CMockIgnoreArg_attr(__LINE__)
void osThreadNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line);
#define osThreadGetId_Ignore() TEST_FAIL_MESSAGE("osThreadGetId requires _IgnoreAndReturn");
#define osThreadGetId_IgnoreAndReturn(cmock_retval) osThreadGetId_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osThreadGetId_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
#define osThreadGetId_StopIgnore() osThreadGetId_CMockStopIgnore()
void osThreadGetId_CMockStopIgnore(void);
#define osThreadGetId_Expect() TEST_FAIL_MESSAGE("osThreadGetId requires _ExpectAndReturn");
#define osThreadGetId_ExpectAndReturn(cmock_retval) osThreadGetId_CMockExpectAndReturn(__LINE__, cmock_retval)
void osThreadGetId_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
typedef osThreadId_t (* CMOCK_osThreadGetId_CALLBACK)(int cmock_num_calls);
void osThreadGetId_AddCallback(CMOCK_osThreadGetId_CALLBACK Callback);
void osThreadGetId_Stub(CMOCK_osThreadGetId_CALLBACK Callback);
#define osThreadGetId_StubWithCallback osThreadGetId_Stub
int osThreadGetId_CallCount(void);
#define osDelay_Ignore() TEST_FAIL_MESSAGE("osDelay requires _IgnoreAndReturn");
#define osDelay_IgnoreAndReturn(cmock_retval) osDelay_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osDelay_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osDelay_StopIgnore() osDelay_CMockStopIgnore()
void osDelay_CMockStopIgnore(void);
#define osDelay_ExpectAnyArgs() TEST_FAIL_MESSAGE("osDelay requires _ExpectAnyArgsAndReturn");
#define osDelay_ExpectAnyArgsAndReturn(cmock_retval) osDelay_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osDelay_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osDelay_Expect(ticks) TEST_FAIL_MESSAGE("osDelay requires _ExpectAndReturn");
#define osDelay_ExpectAndReturn(ticks, cmock_retval) osDelay_CMockExpectAndReturn(__LINE__, ticks, cmock_retval)
void osDelay_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ticks, osStatus_t cmock_to_return);
typedef osStatus_t (* CMOCK_osDelay_CALLBACK)(uint32_t ticks, int cmock_num_calls);
void osDelay_AddCallback(CMOCK_osDelay_CALLBACK Callback);
void osDelay_Stub(CMOCK_osDelay_CALLBACK Callback);
#define osDelay_StubWithCallback osDelay_Stub
int osDelay_CallCount(void);
#define osDelay_IgnoreArg_ticks() osDelay_CMockIgnoreArg_ticks(__LINE__)
void osDelay_CMockIgnoreArg_ticks(UNITY_LINE_TYPE cmock_line);
#define osMutexNew_Ignore() TEST_FAIL_MESSAGE("osMutexNew requires _IgnoreAndReturn");
#define osMutexNew_IgnoreAndReturn(cmock_retval) osMutexNew_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return);
#define osMutexNew_StopIgnore() osMutexNew_CMockStopIgnore()
void osMutexNew_CMockStopIgnore(void);
#define osMutexNew_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexNew requires _ExpectAnyArgsAndReturn");
#define osMutexNew_ExpectAnyArgsAndReturn(cmock_retval) osMutexNew_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return);
#define osMutexNew_Expect(attr) TEST_FAIL_MESSAGE("osMutexNew requires _ExpectAndReturn");
#define osMutexNew_ExpectAndReturn(attr, cmock_retval) osMutexNew_CMockExpectAndReturn(__LINE__, attr, cmock_retval)
void osMutexNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const osMutexAttr_t* attr, osMutexId_t cmock_to_return);
typedef osMutexId_t (* CMOCK_osMutexNew_CALLBACK)(const osMutexAttr_t* attr, int cmock_num_calls);
void osMutexNew_AddCallback(CMOCK_osMutexNew_CALLBACK Callback);
void osMutexNew_Stub(CMOCK_osMutexNew_CALLBACK Callback);
#define osMutexNew_StubWithCallback osMutexNew_Stub
int osMutexNew_CallCount(void);
#define osMutexNew_IgnoreArg_attr() osMutexNew_CMockIgnoreArg_attr(__LINE__)
void osMutexNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line);
#define osMutexAcquire_Ignore() TEST_FAIL_MESSAGE("osMutexAcquire requires _IgnoreAndReturn");
#define osMutexAcquire_IgnoreAndReturn(cmock_retval) osMutexAcquire_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexAcquire_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osMutexAcquire_StopIgnore() osMutexAcquire_CMockStopIgnore()
void osMutexAcquire_CMockStopIgnore(void);
#define osMutexAcquire_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexAcquire requires _ExpectAnyArgsAndReturn");
#define osMutexAcquire_ExpectAnyArgsAndReturn(cmock_retval) osMutexAcquire_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexAcquire_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osMutexAcquire_Expect(mutex_id, timeout) TEST_FAIL_MESSAGE("osMutexAcquire requires _ExpectAndReturn");
#define osMutexAcquire_ExpectAndReturn(mutex_id, timeout, cmock_retval) osMutexAcquire_CMockExpectAndReturn(__LINE__, mutex_id, timeout, cmock_retval)
void osMutexAcquire_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex_id, uint32_t timeout, osStatus_t cmock_to_return);
typedef osStatus_t (* CMOCK_osMutexAcquire_CALLBACK)(osMutexId_t mutex_id, uint32_t timeout, int cmock_num_calls);
void osMutexAcquire_AddCallback(CMOCK_osMutexAcquire_CALLBACK Callback);
void osMutexAcquire_Stub(CMOCK_osMutexAcquire_CALLBACK Callback);
#define osMutexAcquire_StubWithCallback osMutexAcquire_Stub
int osMutexAcquire_CallCount(void);
#define osMutexAcquire_IgnoreArg_mutex_id() osMutexAcquire_CMockIgnoreArg_mutex_id(__LINE__)
void osMutexAcquire_CMockIgnoreArg_mutex_id(UNITY_LINE_TYPE cmock_line);
#define osMutexAcquire_IgnoreArg_timeout() osMutexAcquire_CMockIgnoreArg_timeout(__LINE__)
void osMutexAcquire_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line);
#define osMutexRelease_Ignore() TEST_FAIL_MESSAGE("osMutexRelease requires _IgnoreAndReturn");
#define osMutexRelease_IgnoreAndReturn(cmock_retval) osMutexRelease_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void osMutexRelease_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osMutexRelease_StopIgnore() osMutexRelease_CMockStopIgnore()
void osMutexRelease_CMockStopIgnore(void);
#define osMutexRelease_ExpectAnyArgs() TEST_FAIL_MESSAGE("osMutexRelease requires _ExpectAnyArgsAndReturn");
#define osMutexRelease_ExpectAnyArgsAndReturn(cmock_retval) osMutexRelease_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void osMutexRelease_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return);
#define osMutexRelease_Expect(mutex_id) TEST_FAIL_MESSAGE("osMutexRelease requires _ExpectAndReturn");
#define osMutexRelease_ExpectAndReturn(mutex_id, cmock_retval) osMutexRelease_CMockExpectAndReturn(__LINE__, mutex_id, cmock_retval)
void osMutexRelease_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex_id, osStatus_t cmock_to_return);
typedef osStatus_t (* CMOCK_osMutexRelease_CALLBACK)(osMutexId_t mutex_id, int cmock_num_calls);
void osMutexRelease_AddCallback(CMOCK_osMutexRelease_CALLBACK Callback);
void osMutexRelease_Stub(CMOCK_osMutexRelease_CALLBACK Callback);
#define osMutexRelease_StubWithCallback osMutexRelease_Stub
int osMutexRelease_CallCount(void);
#define osMutexRelease_IgnoreArg_mutex_id() osMutexRelease_CMockIgnoreArg_mutex_id(__LINE__)
void osMutexRelease_CMockIgnoreArg_mutex_id(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
