/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TASK_H
#define _MOCK_TASK_H

#include "unity.h"
#include "task.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_task_Init(void);
void mock_task_Destroy(void);
void mock_task_Verify(void);




#define xTaskGetTickCount_Ignore() TEST_FAIL_MESSAGE("xTaskGetTickCount requires _IgnoreAndReturn");
#define xTaskGetTickCount_IgnoreAndReturn(cmock_retval) xTaskGetTickCount_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xTaskGetTickCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TickType_t cmock_to_return);
#define xTaskGetTickCount_StopIgnore() xTaskGetTickCount_CMockStopIgnore()
void xTaskGetTickCount_CMockStopIgnore(void);
#define xTaskGetTickCount_Expect() TEST_FAIL_MESSAGE("xTaskGetTickCount requires _ExpectAndReturn");
#define xTaskGetTickCount_ExpectAndReturn(cmock_retval) xTaskGetTickCount_CMockExpectAndReturn(__LINE__, cmock_retval)
void xTaskGetTickCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TickType_t cmock_to_return);
typedef TickType_t (* CMOCK_xTaskGetTickCount_CALLBACK)(int cmock_num_calls);
void xTaskGetTickCount_AddCallback(CMOCK_xTaskGetTickCount_CALLBACK Callback);
void xTaskGetTickCount_Stub(CMOCK_xTaskGetTickCount_CALLBACK Callback);
#define xTaskGetTickCount_StubWithCallback xTaskGetTickCount_Stub
int xTaskGetTickCount_CallCount(void);
#define xTaskGetCurrentTaskHandle_Ignore() TEST_FAIL_MESSAGE("xTaskGetCurrentTaskHandle requires _IgnoreAndReturn");
#define xTaskGetCurrentTaskHandle_IgnoreAndReturn(cmock_retval) xTaskGetCurrentTaskHandle_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void xTaskGetCurrentTaskHandle_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return);
#define xTaskGetCurrentTaskHandle_StopIgnore() xTaskGetCurrentTaskHandle_CMockStopIgnore()
void xTaskGetCurrentTaskHandle_CMockStopIgnore(void);
#define xTaskGetCurrentTaskHandle_Expect() TEST_FAIL_MESSAGE("xTaskGetCurrentTaskHandle requires _ExpectAndReturn");
#define xTaskGetCurrentTaskHandle_ExpectAndReturn(cmock_retval) xTaskGetCurrentTaskHandle_CMockExpectAndReturn(__LINE__, cmock_retval)
void xTaskGetCurrentTaskHandle_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TaskHandle_t cmock_to_return);
typedef TaskHandle_t (* CMOCK_xTaskGetCurrentTaskHandle_CALLBACK)(int cmock_num_calls);
void xTaskGetCurrentTaskHandle_AddCallback(CMOCK_xTaskGetCurrentTaskHandle_CALLBACK Callback);
void xTaskGetCurrentTaskHandle_Stub(CMOCK_xTaskGetCurrentTaskHandle_CALLBACK Callback);
#define xTaskGetCurrentTaskHandle_StubWithCallback xTaskGetCurrentTaskHandle_Stub
int xTaskGetCurrentTaskHandle_CallCount(void);
#define vTaskDelay_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vTaskDelay requires _Ignore (not AndReturn)");
#define vTaskDelay_Ignore() vTaskDelay_CMockIgnore()
void vTaskDelay_CMockIgnore(void);
#define vTaskDelay_StopIgnore() vTaskDelay_CMockStopIgnore()
void vTaskDelay_CMockStopIgnore(void);
#define vTaskDelay_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("vTaskDelay requires _ExpectAnyArgs (not AndReturn)");
#define vTaskDelay_ExpectAnyArgs() vTaskDelay_CMockExpectAnyArgs(__LINE__)
void vTaskDelay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define vTaskDelay_ExpectAndReturn(xTicksToDelay, cmock_retval) TEST_FAIL_MESSAGE("vTaskDelay requires _Expect (not AndReturn)");
#define vTaskDelay_Expect(xTicksToDelay) vTaskDelay_CMockExpect(__LINE__, xTicksToDelay)
void vTaskDelay_CMockExpect(UNITY_LINE_TYPE cmock_line, TickType_t xTicksToDelay);
typedef void (* CMOCK_vTaskDelay_CALLBACK)(TickType_t xTicksToDelay, int cmock_num_calls);
void vTaskDelay_AddCallback(CMOCK_vTaskDelay_CALLBACK Callback);
void vTaskDelay_Stub(CMOCK_vTaskDelay_CALLBACK Callback);
#define vTaskDelay_StubWithCallback vTaskDelay_Stub
int vTaskDelay_CallCount(void);
#define vTaskDelay_IgnoreArg_xTicksToDelay() vTaskDelay_CMockIgnoreArg_xTicksToDelay(__LINE__)
void vTaskDelay_CMockIgnoreArg_xTicksToDelay(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
