/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STATE_MACHINE_H
#define _MOCK_STATE_MACHINE_H

#include "unity.h"
#include "state_machine.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_state_machine_Init(void);
void mock_state_machine_Destroy(void);
void mock_state_machine_Verify(void);




#define state_machine_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("state_machine_init requires _Ignore (not AndReturn)");
#define state_machine_init_Ignore() state_machine_init_CMockIgnore()
void state_machine_init_CMockIgnore(void);
#define state_machine_init_StopIgnore() state_machine_init_CMockStopIgnore()
void state_machine_init_CMockStopIgnore(void);
#define state_machine_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("state_machine_init requires _Expect (not AndReturn)");
#define state_machine_init_Expect() state_machine_init_CMockExpect(__LINE__)
void state_machine_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_state_machine_init_CALLBACK)(int cmock_num_calls);
void state_machine_init_AddCallback(CMOCK_state_machine_init_CALLBACK Callback);
void state_machine_init_Stub(CMOCK_state_machine_init_CALLBACK Callback);
#define state_machine_init_StubWithCallback state_machine_init_Stub
int state_machine_init_CallCount(void);
#define state_machine_task_create_Ignore() TEST_FAIL_MESSAGE("state_machine_task_create requires _IgnoreAndReturn");
#define state_machine_task_create_IgnoreAndReturn(cmock_retval) state_machine_task_create_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void state_machine_task_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
#define state_machine_task_create_StopIgnore() state_machine_task_create_CMockStopIgnore()
void state_machine_task_create_CMockStopIgnore(void);
#define state_machine_task_create_Expect() TEST_FAIL_MESSAGE("state_machine_task_create requires _ExpectAndReturn");
#define state_machine_task_create_ExpectAndReturn(cmock_retval) state_machine_task_create_CMockExpectAndReturn(__LINE__, cmock_retval)
void state_machine_task_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
typedef osThreadId_t (* CMOCK_state_machine_task_create_CALLBACK)(int cmock_num_calls);
void state_machine_task_create_AddCallback(CMOCK_state_machine_task_create_CALLBACK Callback);
void state_machine_task_create_Stub(CMOCK_state_machine_task_create_CALLBACK Callback);
#define state_machine_task_create_StubWithCallback state_machine_task_create_Stub
int state_machine_task_create_CallCount(void);
#define state_machine_get_state_Ignore() TEST_FAIL_MESSAGE("state_machine_get_state requires _IgnoreAndReturn");
#define state_machine_get_state_IgnoreAndReturn(cmock_retval) state_machine_get_state_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void state_machine_get_state_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t cmock_to_return);
#define state_machine_get_state_StopIgnore() state_machine_get_state_CMockStopIgnore()
void state_machine_get_state_CMockStopIgnore(void);
#define state_machine_get_state_Expect() TEST_FAIL_MESSAGE("state_machine_get_state requires _ExpectAndReturn");
#define state_machine_get_state_ExpectAndReturn(cmock_retval) state_machine_get_state_CMockExpectAndReturn(__LINE__, cmock_retval)
void state_machine_get_state_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t cmock_to_return);
typedef obw_state_t (* CMOCK_state_machine_get_state_CALLBACK)(int cmock_num_calls);
void state_machine_get_state_AddCallback(CMOCK_state_machine_get_state_CALLBACK Callback);
void state_machine_get_state_Stub(CMOCK_state_machine_get_state_CALLBACK Callback);
#define state_machine_get_state_StubWithCallback state_machine_get_state_Stub
int state_machine_get_state_CallCount(void);
#define state_machine_request_transition_Ignore() TEST_FAIL_MESSAGE("state_machine_request_transition requires _IgnoreAndReturn");
#define state_machine_request_transition_IgnoreAndReturn(cmock_retval) state_machine_request_transition_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void state_machine_request_transition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define state_machine_request_transition_StopIgnore() state_machine_request_transition_CMockStopIgnore()
void state_machine_request_transition_CMockStopIgnore(void);
#define state_machine_request_transition_ExpectAnyArgs() TEST_FAIL_MESSAGE("state_machine_request_transition requires _ExpectAnyArgsAndReturn");
#define state_machine_request_transition_ExpectAnyArgsAndReturn(cmock_retval) state_machine_request_transition_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void state_machine_request_transition_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define state_machine_request_transition_Expect(target, trigger) TEST_FAIL_MESSAGE("state_machine_request_transition requires _ExpectAndReturn");
#define state_machine_request_transition_ExpectAndReturn(target, trigger, cmock_retval) state_machine_request_transition_CMockExpectAndReturn(__LINE__, target, trigger, cmock_retval)
void state_machine_request_transition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t target, uint8_t trigger, int cmock_to_return);
typedef int (* CMOCK_state_machine_request_transition_CALLBACK)(obw_state_t target, uint8_t trigger, int cmock_num_calls);
void state_machine_request_transition_AddCallback(CMOCK_state_machine_request_transition_CALLBACK Callback);
void state_machine_request_transition_Stub(CMOCK_state_machine_request_transition_CALLBACK Callback);
#define state_machine_request_transition_StubWithCallback state_machine_request_transition_Stub
int state_machine_request_transition_CallCount(void);
#define state_machine_request_transition_IgnoreArg_target() state_machine_request_transition_CMockIgnoreArg_target(__LINE__)
void state_machine_request_transition_CMockIgnoreArg_target(UNITY_LINE_TYPE cmock_line);
#define state_machine_request_transition_IgnoreArg_trigger() state_machine_request_transition_CMockIgnoreArg_trigger(__LINE__)
void state_machine_request_transition_CMockIgnoreArg_trigger(UNITY_LINE_TYPE cmock_line);
#define state_machine_get_beacon_interval_Ignore() TEST_FAIL_MESSAGE("state_machine_get_beacon_interval requires _IgnoreAndReturn");
#define state_machine_get_beacon_interval_IgnoreAndReturn(cmock_retval) state_machine_get_beacon_interval_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void state_machine_get_beacon_interval_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define state_machine_get_beacon_interval_StopIgnore() state_machine_get_beacon_interval_CMockStopIgnore()
void state_machine_get_beacon_interval_CMockStopIgnore(void);
#define state_machine_get_beacon_interval_Expect() TEST_FAIL_MESSAGE("state_machine_get_beacon_interval requires _ExpectAndReturn");
#define state_machine_get_beacon_interval_ExpectAndReturn(cmock_retval) state_machine_get_beacon_interval_CMockExpectAndReturn(__LINE__, cmock_retval)
void state_machine_get_beacon_interval_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_state_machine_get_beacon_interval_CALLBACK)(int cmock_num_calls);
void state_machine_get_beacon_interval_AddCallback(CMOCK_state_machine_get_beacon_interval_CALLBACK Callback);
void state_machine_get_beacon_interval_Stub(CMOCK_state_machine_get_beacon_interval_CALLBACK Callback);
#define state_machine_get_beacon_interval_StubWithCallback state_machine_get_beacon_interval_Stub
int state_machine_get_beacon_interval_CallCount(void);
#define state_machine_set_beacon_interval_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("state_machine_set_beacon_interval requires _Ignore (not AndReturn)");
#define state_machine_set_beacon_interval_Ignore() state_machine_set_beacon_interval_CMockIgnore()
void state_machine_set_beacon_interval_CMockIgnore(void);
#define state_machine_set_beacon_interval_StopIgnore() state_machine_set_beacon_interval_CMockStopIgnore()
void state_machine_set_beacon_interval_CMockStopIgnore(void);
#define state_machine_set_beacon_interval_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("state_machine_set_beacon_interval requires _ExpectAnyArgs (not AndReturn)");
#define state_machine_set_beacon_interval_ExpectAnyArgs() state_machine_set_beacon_interval_CMockExpectAnyArgs(__LINE__)
void state_machine_set_beacon_interval_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define state_machine_set_beacon_interval_ExpectAndReturn(interval_ms, cmock_retval) TEST_FAIL_MESSAGE("state_machine_set_beacon_interval requires _Expect (not AndReturn)");
#define state_machine_set_beacon_interval_Expect(interval_ms) state_machine_set_beacon_interval_CMockExpect(__LINE__, interval_ms)
void state_machine_set_beacon_interval_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t interval_ms);
typedef void (* CMOCK_state_machine_set_beacon_interval_CALLBACK)(uint32_t interval_ms, int cmock_num_calls);
void state_machine_set_beacon_interval_AddCallback(CMOCK_state_machine_set_beacon_interval_CALLBACK Callback);
void state_machine_set_beacon_interval_Stub(CMOCK_state_machine_set_beacon_interval_CALLBACK Callback);
#define state_machine_set_beacon_interval_StubWithCallback state_machine_set_beacon_interval_Stub
int state_machine_set_beacon_interval_CallCount(void);
#define state_machine_set_beacon_interval_IgnoreArg_interval_ms() state_machine_set_beacon_interval_CMockIgnoreArg_interval_ms(__LINE__)
void state_machine_set_beacon_interval_CMockIgnoreArg_interval_ms(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
