/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_main.h"

static const char* CMockString_Error_Handler = "Error_Handler";
static const char* CMockString_NVIC_SystemReset = "NVIC_SystemReset";

typedef struct _CMOCK_NVIC_SystemReset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_NVIC_SystemReset_CALL_INSTANCE;

typedef struct _CMOCK_Error_Handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_Error_Handler_CALL_INSTANCE;

static struct mock_mainInstance
{
  char NVIC_SystemReset_IgnoreBool;
  char NVIC_SystemReset_CallbackBool;
  CMOCK_NVIC_SystemReset_CALLBACK NVIC_SystemReset_CallbackFunctionPointer;
  int NVIC_SystemReset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE NVIC_SystemReset_CallInstance;
  char Error_Handler_IgnoreBool;
  char Error_Handler_CallbackBool;
  CMOCK_Error_Handler_CALLBACK Error_Handler_CallbackFunctionPointer;
  int Error_Handler_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Error_Handler_CallInstance;
} Mock;


void mock_main_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.NVIC_SystemReset_CallInstance;
  if (Mock.NVIC_SystemReset_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_NVIC_SystemReset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.NVIC_SystemReset_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Error_Handler_CallInstance;
  if (Mock.Error_Handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Error_Handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Error_Handler_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_main_Init(void)
{
  mock_main_Destroy();
}

void mock_main_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void NVIC_SystemReset(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_NVIC_SystemReset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_NVIC_SystemReset);
  cmock_call_instance = (CMOCK_NVIC_SystemReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.NVIC_SystemReset_CallInstance);
  Mock.NVIC_SystemReset_CallInstance = CMock_Guts_MemNext(Mock.NVIC_SystemReset_CallInstance);
  if (Mock.NVIC_SystemReset_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.NVIC_SystemReset_CallbackBool &&
      Mock.NVIC_SystemReset_CallbackFunctionPointer != NULL)
  {
    Mock.NVIC_SystemReset_CallbackFunctionPointer(Mock.NVIC_SystemReset_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.NVIC_SystemReset_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_NVIC_SystemReset);
    Mock.NVIC_SystemReset_CallbackFunctionPointer(Mock.NVIC_SystemReset_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void NVIC_SystemReset_CMockIgnore(void)
{
  Mock.NVIC_SystemReset_IgnoreBool = (char)1;
}

void NVIC_SystemReset_CMockStopIgnore(void)
{
  Mock.NVIC_SystemReset_IgnoreBool = (char)0;
}

void NVIC_SystemReset_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_NVIC_SystemReset_CALL_INSTANCE));
  CMOCK_NVIC_SystemReset_CALL_INSTANCE* cmock_call_instance = (CMOCK_NVIC_SystemReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.NVIC_SystemReset_CallInstance = CMock_Guts_MemChain(Mock.NVIC_SystemReset_CallInstance, cmock_guts_index);
  Mock.NVIC_SystemReset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void NVIC_SystemReset_AddCallback(CMOCK_NVIC_SystemReset_CALLBACK Callback)
{
  Mock.NVIC_SystemReset_IgnoreBool = (char)0;
  Mock.NVIC_SystemReset_CallbackBool = (char)1;
  Mock.NVIC_SystemReset_CallbackCalls = 0;
  Mock.NVIC_SystemReset_CallbackFunctionPointer = Callback;
}

int NVIC_SystemReset_CallCount(void)
{
  return Mock.NVIC_SystemReset_CallbackCalls;
}

void NVIC_SystemReset_Stub(CMOCK_NVIC_SystemReset_CALLBACK Callback)
{
  Mock.NVIC_SystemReset_IgnoreBool = (char)0;
  Mock.NVIC_SystemReset_CallbackBool = (char)0;
  Mock.NVIC_SystemReset_CallbackCalls = 0;
  Mock.NVIC_SystemReset_CallbackFunctionPointer = Callback;
}

void Error_Handler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Error_Handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Error_Handler);
  cmock_call_instance = (CMOCK_Error_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Error_Handler_CallInstance);
  Mock.Error_Handler_CallInstance = CMock_Guts_MemNext(Mock.Error_Handler_CallInstance);
  if (Mock.Error_Handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Error_Handler_CallbackBool &&
      Mock.Error_Handler_CallbackFunctionPointer != NULL)
  {
    Mock.Error_Handler_CallbackFunctionPointer(Mock.Error_Handler_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.Error_Handler_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Error_Handler);
    Mock.Error_Handler_CallbackFunctionPointer(Mock.Error_Handler_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Error_Handler_CMockIgnore(void)
{
  Mock.Error_Handler_IgnoreBool = (char)1;
}

void Error_Handler_CMockStopIgnore(void)
{
  Mock.Error_Handler_IgnoreBool = (char)0;
}

void Error_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Error_Handler_CALL_INSTANCE));
  CMOCK_Error_Handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Error_Handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Error_Handler_CallInstance = CMock_Guts_MemChain(Mock.Error_Handler_CallInstance, cmock_guts_index);
  Mock.Error_Handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Error_Handler_AddCallback(CMOCK_Error_Handler_CALLBACK Callback)
{
  Mock.Error_Handler_IgnoreBool = (char)0;
  Mock.Error_Handler_CallbackBool = (char)1;
  Mock.Error_Handler_CallbackCalls = 0;
  Mock.Error_Handler_CallbackFunctionPointer = Callback;
}

int Error_Handler_CallCount(void)
{
  return Mock.Error_Handler_CallbackCalls;
}

void Error_Handler_Stub(CMOCK_Error_Handler_CALLBACK Callback)
{
  Mock.Error_Handler_IgnoreBool = (char)0;
  Mock.Error_Handler_CallbackBool = (char)0;
  Mock.Error_Handler_CallbackCalls = 0;
  Mock.Error_Handler_CallbackFunctionPointer = Callback;
}

