/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_WATCHDOG_H
#define _MOCK_WATCHDOG_H

#include "unity.h"
#include "watchdog.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_watchdog_Init(void);
void mock_watchdog_Destroy(void);
void mock_watchdog_Verify(void);




#define watchdog_monitor_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_monitor_init requires _Ignore (not AndReturn)");
#define watchdog_monitor_init_Ignore() watchdog_monitor_init_CMockIgnore()
void watchdog_monitor_init_CMockIgnore(void);
#define watchdog_monitor_init_StopIgnore() watchdog_monitor_init_CMockStopIgnore()
void watchdog_monitor_init_CMockStopIgnore(void);
#define watchdog_monitor_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_monitor_init requires _Expect (not AndReturn)");
#define watchdog_monitor_init_Expect() watchdog_monitor_init_CMockExpect(__LINE__)
void watchdog_monitor_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_watchdog_monitor_init_CALLBACK)(int cmock_num_calls);
void watchdog_monitor_init_AddCallback(CMOCK_watchdog_monitor_init_CALLBACK Callback);
void watchdog_monitor_init_Stub(CMOCK_watchdog_monitor_init_CALLBACK Callback);
#define watchdog_monitor_init_StubWithCallback watchdog_monitor_init_Stub
int watchdog_monitor_init_CallCount(void);
#define watchdog_register_task_Ignore() TEST_FAIL_MESSAGE("watchdog_register_task requires _IgnoreAndReturn");
#define watchdog_register_task_IgnoreAndReturn(cmock_retval) watchdog_register_task_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void watchdog_register_task_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define watchdog_register_task_StopIgnore() watchdog_register_task_CMockStopIgnore()
void watchdog_register_task_CMockStopIgnore(void);
#define watchdog_register_task_ExpectAnyArgs() TEST_FAIL_MESSAGE("watchdog_register_task requires _ExpectAnyArgsAndReturn");
#define watchdog_register_task_ExpectAnyArgsAndReturn(cmock_retval) watchdog_register_task_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void watchdog_register_task_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define watchdog_register_task_Expect(handle, expected_period_ms) TEST_FAIL_MESSAGE("watchdog_register_task requires _ExpectAndReturn");
#define watchdog_register_task_ExpectAndReturn(handle, expected_period_ms, cmock_retval) watchdog_register_task_CMockExpectAndReturn(__LINE__, handle, expected_period_ms, cmock_retval)
void watchdog_register_task_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t handle, uint32_t expected_period_ms, int cmock_to_return);
typedef int (* CMOCK_watchdog_register_task_CALLBACK)(osThreadId_t handle, uint32_t expected_period_ms, int cmock_num_calls);
void watchdog_register_task_AddCallback(CMOCK_watchdog_register_task_CALLBACK Callback);
void watchdog_register_task_Stub(CMOCK_watchdog_register_task_CALLBACK Callback);
#define watchdog_register_task_StubWithCallback watchdog_register_task_Stub
int watchdog_register_task_CallCount(void);
#define watchdog_register_task_IgnoreArg_handle() watchdog_register_task_CMockIgnoreArg_handle(__LINE__)
void watchdog_register_task_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line);
#define watchdog_register_task_IgnoreArg_expected_period_ms() watchdog_register_task_CMockIgnoreArg_expected_period_ms(__LINE__)
void watchdog_register_task_CMockIgnoreArg_expected_period_ms(UNITY_LINE_TYPE cmock_line);
#define watchdog_task_create_Ignore() TEST_FAIL_MESSAGE("watchdog_task_create requires _IgnoreAndReturn");
#define watchdog_task_create_IgnoreAndReturn(cmock_retval) watchdog_task_create_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void watchdog_task_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
#define watchdog_task_create_StopIgnore() watchdog_task_create_CMockStopIgnore()
void watchdog_task_create_CMockStopIgnore(void);
#define watchdog_task_create_Expect() TEST_FAIL_MESSAGE("watchdog_task_create requires _ExpectAndReturn");
#define watchdog_task_create_ExpectAndReturn(cmock_retval) watchdog_task_create_CMockExpectAndReturn(__LINE__, cmock_retval)
void watchdog_task_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return);
typedef osThreadId_t (* CMOCK_watchdog_task_create_CALLBACK)(int cmock_num_calls);
void watchdog_task_create_AddCallback(CMOCK_watchdog_task_create_CALLBACK Callback);
void watchdog_task_create_Stub(CMOCK_watchdog_task_create_CALLBACK Callback);
#define watchdog_task_create_StubWithCallback watchdog_task_create_Stub
int watchdog_task_create_CallCount(void);
#define watchdog_alive_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_alive requires _Ignore (not AndReturn)");
#define watchdog_alive_Ignore() watchdog_alive_CMockIgnore()
void watchdog_alive_CMockIgnore(void);
#define watchdog_alive_StopIgnore() watchdog_alive_CMockStopIgnore()
void watchdog_alive_CMockStopIgnore(void);
#define watchdog_alive_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_alive requires _ExpectAnyArgs (not AndReturn)");
#define watchdog_alive_ExpectAnyArgs() watchdog_alive_CMockExpectAnyArgs(__LINE__)
void watchdog_alive_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define watchdog_alive_ExpectAndReturn(handle, cmock_retval) TEST_FAIL_MESSAGE("watchdog_alive requires _Expect (not AndReturn)");
#define watchdog_alive_Expect(handle) watchdog_alive_CMockExpect(__LINE__, handle)
void watchdog_alive_CMockExpect(UNITY_LINE_TYPE cmock_line, osThreadId_t handle);
typedef void (* CMOCK_watchdog_alive_CALLBACK)(osThreadId_t handle, int cmock_num_calls);
void watchdog_alive_AddCallback(CMOCK_watchdog_alive_CALLBACK Callback);
void watchdog_alive_Stub(CMOCK_watchdog_alive_CALLBACK Callback);
#define watchdog_alive_StubWithCallback watchdog_alive_Stub
int watchdog_alive_CallCount(void);
#define watchdog_alive_IgnoreArg_handle() watchdog_alive_CMockIgnoreArg_handle(__LINE__)
void watchdog_alive_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line);
#define watchdog_alive_self_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_alive_self requires _Ignore (not AndReturn)");
#define watchdog_alive_self_Ignore() watchdog_alive_self_CMockIgnore()
void watchdog_alive_self_CMockIgnore(void);
#define watchdog_alive_self_StopIgnore() watchdog_alive_self_CMockStopIgnore()
void watchdog_alive_self_CMockStopIgnore(void);
#define watchdog_alive_self_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("watchdog_alive_self requires _Expect (not AndReturn)");
#define watchdog_alive_self_Expect() watchdog_alive_self_CMockExpect(__LINE__)
void watchdog_alive_self_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_watchdog_alive_self_CALLBACK)(int cmock_num_calls);
void watchdog_alive_self_AddCallback(CMOCK_watchdog_alive_self_CALLBACK Callback);
void watchdog_alive_self_Stub(CMOCK_watchdog_alive_self_CALLBACK Callback);
#define watchdog_alive_self_StubWithCallback watchdog_alive_self_Stub
int watchdog_alive_self_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
