/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_cmsis_os.h"

static const char* CMockString_argument = "argument";
static const char* CMockString_attr = "attr";
static const char* CMockString_func = "func";
static const char* CMockString_mutex_id = "mutex_id";
static const char* CMockString_osDelay = "osDelay";
static const char* CMockString_osKernelGetTickCount = "osKernelGetTickCount";
static const char* CMockString_osKernelStart = "osKernelStart";
static const char* CMockString_osMutexAcquire = "osMutexAcquire";
static const char* CMockString_osMutexNew = "osMutexNew";
static const char* CMockString_osMutexRelease = "osMutexRelease";
static const char* CMockString_osThreadGetId = "osThreadGetId";
static const char* CMockString_osThreadNew = "osThreadNew";
static const char* CMockString_ticks = "ticks";
static const char* CMockString_timeout = "timeout";

typedef struct _CMOCK_osKernelStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osStatus_t ReturnVal;

} CMOCK_osKernelStart_CALL_INSTANCE;

typedef struct _CMOCK_osKernelGetTickCount_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_osKernelGetTickCount_CALL_INSTANCE;

typedef struct _CMOCK_osThreadNew_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osThreadId_t ReturnVal;
  osThreadFunc_t Expected_func;
  void* Expected_argument;
  const osThreadAttr_t* Expected_attr;
  char ReturnThruPtr_argument_Used;
  void const* ReturnThruPtr_argument_Val;
  size_t ReturnThruPtr_argument_Size;
  char IgnoreArg_func;
  char IgnoreArg_argument;
  char IgnoreArg_attr;

} CMOCK_osThreadNew_CALL_INSTANCE;

typedef struct _CMOCK_osThreadGetId_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osThreadId_t ReturnVal;

} CMOCK_osThreadGetId_CALL_INSTANCE;

typedef struct _CMOCK_osDelay_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osStatus_t ReturnVal;
  uint32_t Expected_ticks;
  char IgnoreArg_ticks;

} CMOCK_osDelay_CALL_INSTANCE;

typedef struct _CMOCK_osMutexNew_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osMutexId_t ReturnVal;
  const osMutexAttr_t* Expected_attr;
  char IgnoreArg_attr;

} CMOCK_osMutexNew_CALL_INSTANCE;

typedef struct _CMOCK_osMutexAcquire_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osStatus_t ReturnVal;
  osMutexId_t Expected_mutex_id;
  uint32_t Expected_timeout;
  char IgnoreArg_mutex_id;
  char IgnoreArg_timeout;

} CMOCK_osMutexAcquire_CALL_INSTANCE;

typedef struct _CMOCK_osMutexRelease_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osStatus_t ReturnVal;
  osMutexId_t Expected_mutex_id;
  char IgnoreArg_mutex_id;

} CMOCK_osMutexRelease_CALL_INSTANCE;

static struct mock_cmsis_osInstance
{
  char osKernelStart_IgnoreBool;
  osStatus_t osKernelStart_FinalReturn;
  char osKernelStart_CallbackBool;
  CMOCK_osKernelStart_CALLBACK osKernelStart_CallbackFunctionPointer;
  int osKernelStart_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osKernelStart_CallInstance;
  char osKernelGetTickCount_IgnoreBool;
  uint32_t osKernelGetTickCount_FinalReturn;
  char osKernelGetTickCount_CallbackBool;
  CMOCK_osKernelGetTickCount_CALLBACK osKernelGetTickCount_CallbackFunctionPointer;
  int osKernelGetTickCount_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osKernelGetTickCount_CallInstance;
  char osThreadNew_IgnoreBool;
  osThreadId_t osThreadNew_FinalReturn;
  char osThreadNew_CallbackBool;
  CMOCK_osThreadNew_CALLBACK osThreadNew_CallbackFunctionPointer;
  int osThreadNew_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osThreadNew_CallInstance;
  char osThreadGetId_IgnoreBool;
  osThreadId_t osThreadGetId_FinalReturn;
  char osThreadGetId_CallbackBool;
  CMOCK_osThreadGetId_CALLBACK osThreadGetId_CallbackFunctionPointer;
  int osThreadGetId_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osThreadGetId_CallInstance;
  char osDelay_IgnoreBool;
  osStatus_t osDelay_FinalReturn;
  char osDelay_CallbackBool;
  CMOCK_osDelay_CALLBACK osDelay_CallbackFunctionPointer;
  int osDelay_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osDelay_CallInstance;
  char osMutexNew_IgnoreBool;
  osMutexId_t osMutexNew_FinalReturn;
  char osMutexNew_CallbackBool;
  CMOCK_osMutexNew_CALLBACK osMutexNew_CallbackFunctionPointer;
  int osMutexNew_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osMutexNew_CallInstance;
  char osMutexAcquire_IgnoreBool;
  osStatus_t osMutexAcquire_FinalReturn;
  char osMutexAcquire_CallbackBool;
  CMOCK_osMutexAcquire_CALLBACK osMutexAcquire_CallbackFunctionPointer;
  int osMutexAcquire_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osMutexAcquire_CallInstance;
  char osMutexRelease_IgnoreBool;
  osStatus_t osMutexRelease_FinalReturn;
  char osMutexRelease_CallbackBool;
  CMOCK_osMutexRelease_CALLBACK osMutexRelease_CallbackFunctionPointer;
  int osMutexRelease_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE osMutexRelease_CallInstance;
} Mock;


void mock_cmsis_os_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.osKernelStart_CallInstance;
  if (Mock.osKernelStart_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osKernelStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osKernelStart_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osKernelGetTickCount_CallInstance;
  if (Mock.osKernelGetTickCount_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osKernelGetTickCount);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osKernelGetTickCount_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osThreadNew_CallInstance;
  if (Mock.osThreadNew_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osThreadNew);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osThreadNew_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osThreadGetId_CallInstance;
  if (Mock.osThreadGetId_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osThreadGetId);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osThreadGetId_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osDelay_CallInstance;
  if (Mock.osDelay_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osDelay);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osDelay_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osMutexNew_CallInstance;
  if (Mock.osMutexNew_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osMutexNew);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osMutexNew_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osMutexAcquire_CallInstance;
  if (Mock.osMutexAcquire_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osMutexAcquire);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osMutexAcquire_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.osMutexRelease_CallInstance;
  if (Mock.osMutexRelease_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_osMutexRelease);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.osMutexRelease_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_cmsis_os_Init(void)
{
  mock_cmsis_os_Destroy();
}

void mock_cmsis_os_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

osStatus_t osKernelStart(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osKernelStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osKernelStart);
  cmock_call_instance = (CMOCK_osKernelStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osKernelStart_CallInstance);
  Mock.osKernelStart_CallInstance = CMock_Guts_MemNext(Mock.osKernelStart_CallInstance);
  if (Mock.osKernelStart_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osKernelStart_FinalReturn;
    Mock.osKernelStart_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osKernelStart_CallbackBool &&
      Mock.osKernelStart_CallbackFunctionPointer != NULL)
  {
    osStatus_t cmock_cb_ret = Mock.osKernelStart_CallbackFunctionPointer(Mock.osKernelStart_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.osKernelStart_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osKernelStart);
    cmock_call_instance->ReturnVal = Mock.osKernelStart_CallbackFunctionPointer(Mock.osKernelStart_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void osKernelStart_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osKernelStart_CALL_INSTANCE));
  CMOCK_osKernelStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_osKernelStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osKernelStart_CallInstance = CMock_Guts_MemChain(Mock.osKernelStart_CallInstance, cmock_guts_index);
  Mock.osKernelStart_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osKernelStart_IgnoreBool = (char)1;
}

void osKernelStart_CMockStopIgnore(void)
{
  if(Mock.osKernelStart_IgnoreBool)
    Mock.osKernelStart_CallInstance = CMock_Guts_MemNext(Mock.osKernelStart_CallInstance);
  Mock.osKernelStart_IgnoreBool = (char)0;
}

void osKernelStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osKernelStart_CALL_INSTANCE));
  CMOCK_osKernelStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_osKernelStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osKernelStart_CallInstance = CMock_Guts_MemChain(Mock.osKernelStart_CallInstance, cmock_guts_index);
  Mock.osKernelStart_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osKernelStart_AddCallback(CMOCK_osKernelStart_CALLBACK Callback)
{
  Mock.osKernelStart_IgnoreBool = (char)0;
  Mock.osKernelStart_CallbackBool = (char)1;
  Mock.osKernelStart_CallbackCalls = 0;
  Mock.osKernelStart_CallbackFunctionPointer = Callback;
}

int osKernelStart_CallCount(void)
{
  return Mock.osKernelStart_CallbackCalls;
}

void osKernelStart_Stub(CMOCK_osKernelStart_CALLBACK Callback)
{
  Mock.osKernelStart_IgnoreBool = (char)0;
  Mock.osKernelStart_CallbackBool = (char)0;
  Mock.osKernelStart_CallbackCalls = 0;
  Mock.osKernelStart_CallbackFunctionPointer = Callback;
}

uint32_t osKernelGetTickCount(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osKernelGetTickCount_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osKernelGetTickCount);
  cmock_call_instance = (CMOCK_osKernelGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osKernelGetTickCount_CallInstance);
  Mock.osKernelGetTickCount_CallInstance = CMock_Guts_MemNext(Mock.osKernelGetTickCount_CallInstance);
  if (Mock.osKernelGetTickCount_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osKernelGetTickCount_FinalReturn;
    Mock.osKernelGetTickCount_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osKernelGetTickCount_CallbackBool &&
      Mock.osKernelGetTickCount_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.osKernelGetTickCount_CallbackFunctionPointer(Mock.osKernelGetTickCount_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.osKernelGetTickCount_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osKernelGetTickCount);
    cmock_call_instance->ReturnVal = Mock.osKernelGetTickCount_CallbackFunctionPointer(Mock.osKernelGetTickCount_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void osKernelGetTickCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osKernelGetTickCount_CALL_INSTANCE));
  CMOCK_osKernelGetTickCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_osKernelGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osKernelGetTickCount_CallInstance = CMock_Guts_MemChain(Mock.osKernelGetTickCount_CallInstance, cmock_guts_index);
  Mock.osKernelGetTickCount_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osKernelGetTickCount_IgnoreBool = (char)1;
}

void osKernelGetTickCount_CMockStopIgnore(void)
{
  if(Mock.osKernelGetTickCount_IgnoreBool)
    Mock.osKernelGetTickCount_CallInstance = CMock_Guts_MemNext(Mock.osKernelGetTickCount_CallInstance);
  Mock.osKernelGetTickCount_IgnoreBool = (char)0;
}

void osKernelGetTickCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osKernelGetTickCount_CALL_INSTANCE));
  CMOCK_osKernelGetTickCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_osKernelGetTickCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osKernelGetTickCount_CallInstance = CMock_Guts_MemChain(Mock.osKernelGetTickCount_CallInstance, cmock_guts_index);
  Mock.osKernelGetTickCount_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osKernelGetTickCount_AddCallback(CMOCK_osKernelGetTickCount_CALLBACK Callback)
{
  Mock.osKernelGetTickCount_IgnoreBool = (char)0;
  Mock.osKernelGetTickCount_CallbackBool = (char)1;
  Mock.osKernelGetTickCount_CallbackCalls = 0;
  Mock.osKernelGetTickCount_CallbackFunctionPointer = Callback;
}

int osKernelGetTickCount_CallCount(void)
{
  return Mock.osKernelGetTickCount_CallbackCalls;
}

void osKernelGetTickCount_Stub(CMOCK_osKernelGetTickCount_CALLBACK Callback)
{
  Mock.osKernelGetTickCount_IgnoreBool = (char)0;
  Mock.osKernelGetTickCount_CallbackBool = (char)0;
  Mock.osKernelGetTickCount_CallbackCalls = 0;
  Mock.osKernelGetTickCount_CallbackFunctionPointer = Callback;
}

osThreadId_t osThreadNew(osThreadFunc_t func, void* argument, const osThreadAttr_t* attr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osThreadNew);
  cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osThreadNew_CallInstance);
  Mock.osThreadNew_CallInstance = CMock_Guts_MemNext(Mock.osThreadNew_CallInstance);
  if (Mock.osThreadNew_IgnoreBool && cmock_call_instance != NULL &&
      cmock_call_instance->ReturnThruPtr_argument_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(argument, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)argument, (const void*)cmock_call_instance->ReturnThruPtr_argument_Val,
      cmock_call_instance->ReturnThruPtr_argument_Size);
  }
  if (Mock.osThreadNew_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osThreadNew_FinalReturn;
    memcpy((void*)(&Mock.osThreadNew_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(osThreadId_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osThreadNew_CallbackBool &&
      Mock.osThreadNew_CallbackFunctionPointer != NULL)
  {
    osThreadId_t cmock_cb_ret = Mock.osThreadNew_CallbackFunctionPointer(func, argument, attr, Mock.osThreadNew_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_func)
  {
    UNITY_SET_DETAILS(CMockString_osThreadNew,CMockString_func);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_func, &func, sizeof(osThreadFunc_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_argument)
  {
    UNITY_SET_DETAILS(CMockString_osThreadNew,CMockString_argument);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_argument, argument, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_attr)
  {
    UNITY_SET_DETAILS(CMockString_osThreadNew,CMockString_attr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_attr, attr, sizeof(const osThreadAttr_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.osThreadNew_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osThreadNew);
    cmock_call_instance->ReturnVal = Mock.osThreadNew_CallbackFunctionPointer(func, argument, attr, Mock.osThreadNew_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_argument_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(argument, cmock_line, CMockStringPtrIsNULL);
    CMOCK_MEMCPY((void*)argument, (const void*)cmock_call_instance->ReturnThruPtr_argument_Val,
      cmock_call_instance->ReturnThruPtr_argument_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osThreadNew(CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance, osThreadFunc_t func, void* argument, const osThreadAttr_t* attr);
void CMockExpectParameters_osThreadNew(CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance, osThreadFunc_t func, void* argument, const osThreadAttr_t* attr)
{
  memcpy((void*)(&cmock_call_instance->Expected_func), (const void*)(&func),
         sizeof(osThreadFunc_t[sizeof(func) == sizeof(osThreadFunc_t) ? 1 : -1])); /* add osThreadFunc_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_func = 0;
  cmock_call_instance->Expected_argument = argument;
  cmock_call_instance->IgnoreArg_argument = 0;
  cmock_call_instance->ReturnThruPtr_argument_Used = 0;
  cmock_call_instance->Expected_attr = attr;
  cmock_call_instance->IgnoreArg_attr = 0;
}

void osThreadNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadNew_CALL_INSTANCE));
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osThreadNew_CallInstance = CMock_Guts_MemChain(Mock.osThreadNew_CallInstance, cmock_guts_index);
  Mock.osThreadNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osThreadNew_IgnoreBool = (char)1;
}

void osThreadNew_CMockStopIgnore(void)
{
  if(Mock.osThreadNew_IgnoreBool)
    Mock.osThreadNew_CallInstance = CMock_Guts_MemNext(Mock.osThreadNew_CallInstance);
  Mock.osThreadNew_IgnoreBool = (char)0;
}

void osThreadNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadNew_CALL_INSTANCE));
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osThreadNew_CallInstance = CMock_Guts_MemChain(Mock.osThreadNew_CallInstance, cmock_guts_index);
  Mock.osThreadNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void osThreadNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadFunc_t func, void* argument, const osThreadAttr_t* attr, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadNew_CALL_INSTANCE));
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osThreadNew_CallInstance = CMock_Guts_MemChain(Mock.osThreadNew_CallInstance, cmock_guts_index);
  Mock.osThreadNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_osThreadNew(cmock_call_instance, func, argument, attr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(osThreadId_t[sizeof(cmock_to_return) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
}

void osThreadNew_AddCallback(CMOCK_osThreadNew_CALLBACK Callback)
{
  Mock.osThreadNew_IgnoreBool = (char)0;
  Mock.osThreadNew_CallbackBool = (char)1;
  Mock.osThreadNew_CallbackCalls = 0;
  Mock.osThreadNew_CallbackFunctionPointer = Callback;
}

int osThreadNew_CallCount(void)
{
  return Mock.osThreadNew_CallbackCalls;
}

void osThreadNew_Stub(CMOCK_osThreadNew_CALLBACK Callback)
{
  Mock.osThreadNew_IgnoreBool = (char)0;
  Mock.osThreadNew_CallbackBool = (char)0;
  Mock.osThreadNew_CallbackCalls = 0;
  Mock.osThreadNew_CallbackFunctionPointer = Callback;
}

void osThreadNew_CMockReturnMemThruPtr_argument(UNITY_LINE_TYPE cmock_line, void const* argument, size_t cmock_size)
{
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osThreadNew_CallInstance));
  if (Mock.osThreadNew_IgnoreBool &&
      (cmock_call_instance == NULL || cmock_call_instance->ReturnThruPtr_argument_Used))
  {
    CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadNew_CALL_INSTANCE));
    CMOCK_osThreadNew_CALL_INSTANCE* new_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
    UNITY_TEST_ASSERT_NOT_NULL(new_instance, cmock_line, CMockStringOutOfMemory);
    memset(new_instance, 0, sizeof(*new_instance));
    new_instance->LineNumber = cmock_line;
    if (cmock_call_instance != NULL)
      new_instance->ReturnVal = cmock_call_instance->ReturnVal;
    Mock.osThreadNew_CallInstance = CMock_Guts_MemChain(Mock.osThreadNew_CallInstance, cmock_guts_index);
    cmock_call_instance = new_instance;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_argument_Used = 1;
  cmock_call_instance->ReturnThruPtr_argument_Val = argument;
  cmock_call_instance->ReturnThruPtr_argument_Size = cmock_size;
}

void osThreadNew_CMockIgnoreArg_func(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osThreadNew_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_func = 1;
}

void osThreadNew_CMockIgnoreArg_argument(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osThreadNew_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_argument = 1;
}

void osThreadNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osThreadNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osThreadNew_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_attr = 1;
}

osThreadId_t osThreadGetId(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osThreadGetId_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osThreadGetId);
  cmock_call_instance = (CMOCK_osThreadGetId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osThreadGetId_CallInstance);
  Mock.osThreadGetId_CallInstance = CMock_Guts_MemNext(Mock.osThreadGetId_CallInstance);
  if (Mock.osThreadGetId_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osThreadGetId_FinalReturn;
    memcpy((void*)(&Mock.osThreadGetId_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(osThreadId_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osThreadGetId_CallbackBool &&
      Mock.osThreadGetId_CallbackFunctionPointer != NULL)
  {
    osThreadId_t cmock_cb_ret = Mock.osThreadGetId_CallbackFunctionPointer(Mock.osThreadGetId_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.osThreadGetId_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osThreadGetId);
    cmock_call_instance->ReturnVal = Mock.osThreadGetId_CallbackFunctionPointer(Mock.osThreadGetId_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void osThreadGetId_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadGetId_CALL_INSTANCE));
  CMOCK_osThreadGetId_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadGetId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osThreadGetId_CallInstance = CMock_Guts_MemChain(Mock.osThreadGetId_CallInstance, cmock_guts_index);
  Mock.osThreadGetId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osThreadGetId_IgnoreBool = (char)1;
}

void osThreadGetId_CMockStopIgnore(void)
{
  if(Mock.osThreadGetId_IgnoreBool)
    Mock.osThreadGetId_CallInstance = CMock_Guts_MemNext(Mock.osThreadGetId_CallInstance);
  Mock.osThreadGetId_IgnoreBool = (char)0;
}

void osThreadGetId_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osThreadGetId_CALL_INSTANCE));
  CMOCK_osThreadGetId_CALL_INSTANCE* cmock_call_instance = (CMOCK_osThreadGetId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osThreadGetId_CallInstance = CMock_Guts_MemChain(Mock.osThreadGetId_CallInstance, cmock_guts_index);
  Mock.osThreadGetId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(osThreadId_t[sizeof(cmock_to_return) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
}

void osThreadGetId_AddCallback(CMOCK_osThreadGetId_CALLBACK Callback)
{
  Mock.osThreadGetId_IgnoreBool = (char)0;
  Mock.osThreadGetId_CallbackBool = (char)1;
  Mock.osThreadGetId_CallbackCalls = 0;
  Mock.osThreadGetId_CallbackFunctionPointer = Callback;
}

int osThreadGetId_CallCount(void)
{
  return Mock.osThreadGetId_CallbackCalls;
}

void osThreadGetId_Stub(CMOCK_osThreadGetId_CALLBACK Callback)
{
  Mock.osThreadGetId_IgnoreBool = (char)0;
  Mock.osThreadGetId_CallbackBool = (char)0;
  Mock.osThreadGetId_CallbackCalls = 0;
  Mock.osThreadGetId_CallbackFunctionPointer = Callback;
}

osStatus_t osDelay(uint32_t ticks)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osDelay);
  cmock_call_instance = (CMOCK_osDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osDelay_CallInstance);
  Mock.osDelay_CallInstance = CMock_Guts_MemNext(Mock.osDelay_CallInstance);
  if (Mock.osDelay_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osDelay_FinalReturn;
    Mock.osDelay_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osDelay_CallbackBool &&
      Mock.osDelay_CallbackFunctionPointer != NULL)
  {
    osStatus_t cmock_cb_ret = Mock.osDelay_CallbackFunctionPointer(ticks, Mock.osDelay_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_ticks)
  {
    UNITY_SET_DETAILS(CMockString_osDelay,CMockString_ticks);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ticks, ticks, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.osDelay_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osDelay);
    cmock_call_instance->ReturnVal = Mock.osDelay_CallbackFunctionPointer(ticks, Mock.osDelay_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osDelay(CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance, uint32_t ticks);
void CMockExpectParameters_osDelay(CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance, uint32_t ticks)
{
  cmock_call_instance->Expected_ticks = ticks;
  cmock_call_instance->IgnoreArg_ticks = 0;
}

void osDelay_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osDelay_CALL_INSTANCE));
  CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_osDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osDelay_CallInstance = CMock_Guts_MemChain(Mock.osDelay_CallInstance, cmock_guts_index);
  Mock.osDelay_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osDelay_IgnoreBool = (char)1;
}

void osDelay_CMockStopIgnore(void)
{
  if(Mock.osDelay_IgnoreBool)
    Mock.osDelay_CallInstance = CMock_Guts_MemNext(Mock.osDelay_CallInstance);
  Mock.osDelay_IgnoreBool = (char)0;
}

void osDelay_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osDelay_CALL_INSTANCE));
  CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_osDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osDelay_CallInstance = CMock_Guts_MemChain(Mock.osDelay_CallInstance, cmock_guts_index);
  Mock.osDelay_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void osDelay_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ticks, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osDelay_CALL_INSTANCE));
  CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_osDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osDelay_CallInstance = CMock_Guts_MemChain(Mock.osDelay_CallInstance, cmock_guts_index);
  Mock.osDelay_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_osDelay(cmock_call_instance, ticks);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osDelay_AddCallback(CMOCK_osDelay_CALLBACK Callback)
{
  Mock.osDelay_IgnoreBool = (char)0;
  Mock.osDelay_CallbackBool = (char)1;
  Mock.osDelay_CallbackCalls = 0;
  Mock.osDelay_CallbackFunctionPointer = Callback;
}

int osDelay_CallCount(void)
{
  return Mock.osDelay_CallbackCalls;
}

void osDelay_Stub(CMOCK_osDelay_CALLBACK Callback)
{
  Mock.osDelay_IgnoreBool = (char)0;
  Mock.osDelay_CallbackBool = (char)0;
  Mock.osDelay_CallbackCalls = 0;
  Mock.osDelay_CallbackFunctionPointer = Callback;
}

void osDelay_CMockIgnoreArg_ticks(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_osDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osDelay_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ticks = 1;
}

osMutexId_t osMutexNew(const osMutexAttr_t* attr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osMutexNew);
  cmock_call_instance = (CMOCK_osMutexNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osMutexNew_CallInstance);
  Mock.osMutexNew_CallInstance = CMock_Guts_MemNext(Mock.osMutexNew_CallInstance);
  if (Mock.osMutexNew_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osMutexNew_FinalReturn;
    memcpy((void*)(&Mock.osMutexNew_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(osMutexId_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(osMutexId_t) ? 1 : -1])); /* add osMutexId_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osMutexNew_CallbackBool &&
      Mock.osMutexNew_CallbackFunctionPointer != NULL)
  {
    osMutexId_t cmock_cb_ret = Mock.osMutexNew_CallbackFunctionPointer(attr, Mock.osMutexNew_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_attr)
  {
    UNITY_SET_DETAILS(CMockString_osMutexNew,CMockString_attr);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_attr, attr, sizeof(const osMutexAttr_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.osMutexNew_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osMutexNew);
    cmock_call_instance->ReturnVal = Mock.osMutexNew_CallbackFunctionPointer(attr, Mock.osMutexNew_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osMutexNew(CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance, const osMutexAttr_t* attr);
void CMockExpectParameters_osMutexNew(CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance, const osMutexAttr_t* attr)
{
  cmock_call_instance->Expected_attr = attr;
  cmock_call_instance->IgnoreArg_attr = 0;
}

void osMutexNew_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexNew_CALL_INSTANCE));
  CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexNew_CallInstance = CMock_Guts_MemChain(Mock.osMutexNew_CallInstance, cmock_guts_index);
  Mock.osMutexNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osMutexNew_IgnoreBool = (char)1;
}

void osMutexNew_CMockStopIgnore(void)
{
  if(Mock.osMutexNew_IgnoreBool)
    Mock.osMutexNew_CallInstance = CMock_Guts_MemNext(Mock.osMutexNew_CallInstance);
  Mock.osMutexNew_IgnoreBool = (char)0;
}

void osMutexNew_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexNew_CALL_INSTANCE));
  CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexNew_CallInstance = CMock_Guts_MemChain(Mock.osMutexNew_CallInstance, cmock_guts_index);
  Mock.osMutexNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void osMutexNew_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const osMutexAttr_t* attr, osMutexId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexNew_CALL_INSTANCE));
  CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexNew_CallInstance = CMock_Guts_MemChain(Mock.osMutexNew_CallInstance, cmock_guts_index);
  Mock.osMutexNew_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_osMutexNew(cmock_call_instance, attr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(osMutexId_t[sizeof(cmock_to_return) == sizeof(osMutexId_t) ? 1 : -1])); /* add osMutexId_t to :treat_as_array if this causes an error */
}

void osMutexNew_AddCallback(CMOCK_osMutexNew_CALLBACK Callback)
{
  Mock.osMutexNew_IgnoreBool = (char)0;
  Mock.osMutexNew_CallbackBool = (char)1;
  Mock.osMutexNew_CallbackCalls = 0;
  Mock.osMutexNew_CallbackFunctionPointer = Callback;
}

int osMutexNew_CallCount(void)
{
  return Mock.osMutexNew_CallbackCalls;
}

void osMutexNew_Stub(CMOCK_osMutexNew_CALLBACK Callback)
{
  Mock.osMutexNew_IgnoreBool = (char)0;
  Mock.osMutexNew_CallbackBool = (char)0;
  Mock.osMutexNew_CallbackCalls = 0;
  Mock.osMutexNew_CallbackFunctionPointer = Callback;
}

void osMutexNew_CMockIgnoreArg_attr(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osMutexNew_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexNew_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osMutexNew_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_attr = 1;
}

osStatus_t osMutexAcquire(osMutexId_t mutex_id, uint32_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osMutexAcquire);
  cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osMutexAcquire_CallInstance);
  Mock.osMutexAcquire_CallInstance = CMock_Guts_MemNext(Mock.osMutexAcquire_CallInstance);
  if (Mock.osMutexAcquire_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osMutexAcquire_FinalReturn;
    Mock.osMutexAcquire_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osMutexAcquire_CallbackBool &&
      Mock.osMutexAcquire_CallbackFunctionPointer != NULL)
  {
    osStatus_t cmock_cb_ret = Mock.osMutexAcquire_CallbackFunctionPointer(mutex_id, timeout, Mock.osMutexAcquire_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_mutex_id)
  {
    UNITY_SET_DETAILS(CMockString_osMutexAcquire,CMockString_mutex_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_mutex_id, &mutex_id, sizeof(osMutexId_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_osMutexAcquire,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.osMutexAcquire_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osMutexAcquire);
    cmock_call_instance->ReturnVal = Mock.osMutexAcquire_CallbackFunctionPointer(mutex_id, timeout, Mock.osMutexAcquire_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osMutexAcquire(CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance, osMutexId_t mutex_id, uint32_t timeout);
void CMockExpectParameters_osMutexAcquire(CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance, osMutexId_t mutex_id, uint32_t timeout)
{
  memcpy((void*)(&cmock_call_instance->Expected_mutex_id), (const void*)(&mutex_id),
         sizeof(osMutexId_t[sizeof(mutex_id) == sizeof(osMutexId_t) ? 1 : -1])); /* add osMutexId_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_mutex_id = 0;
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void osMutexAcquire_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexAcquire_CALL_INSTANCE));
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexAcquire_CallInstance = CMock_Guts_MemChain(Mock.osMutexAcquire_CallInstance, cmock_guts_index);
  Mock.osMutexAcquire_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osMutexAcquire_IgnoreBool = (char)1;
}

void osMutexAcquire_CMockStopIgnore(void)
{
  if(Mock.osMutexAcquire_IgnoreBool)
    Mock.osMutexAcquire_CallInstance = CMock_Guts_MemNext(Mock.osMutexAcquire_CallInstance);
  Mock.osMutexAcquire_IgnoreBool = (char)0;
}

void osMutexAcquire_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexAcquire_CALL_INSTANCE));
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexAcquire_CallInstance = CMock_Guts_MemChain(Mock.osMutexAcquire_CallInstance, cmock_guts_index);
  Mock.osMutexAcquire_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void osMutexAcquire_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex_id, uint32_t timeout, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexAcquire_CALL_INSTANCE));
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexAcquire_CallInstance = CMock_Guts_MemChain(Mock.osMutexAcquire_CallInstance, cmock_guts_index);
  Mock.osMutexAcquire_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_osMutexAcquire(cmock_call_instance, mutex_id, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osMutexAcquire_AddCallback(CMOCK_osMutexAcquire_CALLBACK Callback)
{
  Mock.osMutexAcquire_IgnoreBool = (char)0;
  Mock.osMutexAcquire_CallbackBool = (char)1;
  Mock.osMutexAcquire_CallbackCalls = 0;
  Mock.osMutexAcquire_CallbackFunctionPointer = Callback;
}

int osMutexAcquire_CallCount(void)
{
  return Mock.osMutexAcquire_CallbackCalls;
}

void osMutexAcquire_Stub(CMOCK_osMutexAcquire_CALLBACK Callback)
{
  Mock.osMutexAcquire_IgnoreBool = (char)0;
  Mock.osMutexAcquire_CallbackBool = (char)0;
  Mock.osMutexAcquire_CallbackCalls = 0;
  Mock.osMutexAcquire_CallbackFunctionPointer = Callback;
}

void osMutexAcquire_CMockIgnoreArg_mutex_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osMutexAcquire_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mutex_id = 1;
}

void osMutexAcquire_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osMutexAcquire_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexAcquire_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osMutexAcquire_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

osStatus_t osMutexRelease(osMutexId_t mutex_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_osMutexRelease);
  cmock_call_instance = (CMOCK_osMutexRelease_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.osMutexRelease_CallInstance);
  Mock.osMutexRelease_CallInstance = CMock_Guts_MemNext(Mock.osMutexRelease_CallInstance);
  if (Mock.osMutexRelease_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.osMutexRelease_FinalReturn;
    Mock.osMutexRelease_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.osMutexRelease_CallbackBool &&
      Mock.osMutexRelease_CallbackFunctionPointer != NULL)
  {
    osStatus_t cmock_cb_ret = Mock.osMutexRelease_CallbackFunctionPointer(mutex_id, Mock.osMutexRelease_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_mutex_id)
  {
    UNITY_SET_DETAILS(CMockString_osMutexRelease,CMockString_mutex_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_mutex_id, &mutex_id, sizeof(osMutexId_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.osMutexRelease_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_osMutexRelease);
    cmock_call_instance->ReturnVal = Mock.osMutexRelease_CallbackFunctionPointer(mutex_id, Mock.osMutexRelease_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_osMutexRelease(CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance, osMutexId_t mutex_id);
void CMockExpectParameters_osMutexRelease(CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance, osMutexId_t mutex_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_mutex_id), (const void*)(&mutex_id),
         sizeof(osMutexId_t[sizeof(mutex_id) == sizeof(osMutexId_t) ? 1 : -1])); /* add osMutexId_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_mutex_id = 0;
}

void osMutexRelease_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexRelease_CALL_INSTANCE));
  CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexRelease_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexRelease_CallInstance = CMock_Guts_MemChain(Mock.osMutexRelease_CallInstance, cmock_guts_index);
  Mock.osMutexRelease_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.osMutexRelease_IgnoreBool = (char)1;
}

void osMutexRelease_CMockStopIgnore(void)
{
  if(Mock.osMutexRelease_IgnoreBool)
    Mock.osMutexRelease_CallInstance = CMock_Guts_MemNext(Mock.osMutexRelease_CallInstance);
  Mock.osMutexRelease_IgnoreBool = (char)0;
}

void osMutexRelease_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexRelease_CALL_INSTANCE));
  CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexRelease_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexRelease_CallInstance = CMock_Guts_MemChain(Mock.osMutexRelease_CallInstance, cmock_guts_index);
  Mock.osMutexRelease_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void osMutexRelease_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osMutexId_t mutex_id, osStatus_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_osMutexRelease_CALL_INSTANCE));
  CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexRelease_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.osMutexRelease_CallInstance = CMock_Guts_MemChain(Mock.osMutexRelease_CallInstance, cmock_guts_index);
  Mock.osMutexRelease_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_osMutexRelease(cmock_call_instance, mutex_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void osMutexRelease_AddCallback(CMOCK_osMutexRelease_CALLBACK Callback)
{
  Mock.osMutexRelease_IgnoreBool = (char)0;
  Mock.osMutexRelease_CallbackBool = (char)1;
  Mock.osMutexRelease_CallbackCalls = 0;
  Mock.osMutexRelease_CallbackFunctionPointer = Callback;
}

int osMutexRelease_CallCount(void)
{
  return Mock.osMutexRelease_CallbackCalls;
}

void osMutexRelease_Stub(CMOCK_osMutexRelease_CALLBACK Callback)
{
  Mock.osMutexRelease_IgnoreBool = (char)0;
  Mock.osMutexRelease_CallbackBool = (char)0;
  Mock.osMutexRelease_CallbackCalls = 0;
  Mock.osMutexRelease_CallbackFunctionPointer = Callback;
}

void osMutexRelease_CMockIgnoreArg_mutex_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_osMutexRelease_CALL_INSTANCE* cmock_call_instance = (CMOCK_osMutexRelease_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.osMutexRelease_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mutex_id = 1;
}

