/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_watchdog.h"

static const char* CMockString_expected_period_ms = "expected_period_ms";
static const char* CMockString_handle = "handle";
static const char* CMockString_watchdog_alive = "watchdog_alive";
static const char* CMockString_watchdog_alive_self = "watchdog_alive_self";
static const char* CMockString_watchdog_monitor_init = "watchdog_monitor_init";
static const char* CMockString_watchdog_register_task = "watchdog_register_task";
static const char* CMockString_watchdog_task_create = "watchdog_task_create";

typedef struct _CMOCK_watchdog_monitor_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_watchdog_monitor_init_CALL_INSTANCE;

typedef struct _CMOCK_watchdog_register_task_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  osThreadId_t Expected_handle;
  uint32_t Expected_expected_period_ms;
  char IgnoreArg_handle;
  char IgnoreArg_expected_period_ms;

} CMOCK_watchdog_register_task_CALL_INSTANCE;

typedef struct _CMOCK_watchdog_task_create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osThreadId_t ReturnVal;

} CMOCK_watchdog_task_create_CALL_INSTANCE;

typedef struct _CMOCK_watchdog_alive_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osThreadId_t Expected_handle;
  char IgnoreArg_handle;

} CMOCK_watchdog_alive_CALL_INSTANCE;

typedef struct _CMOCK_watchdog_alive_self_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_watchdog_alive_self_CALL_INSTANCE;

static struct mock_watchdogInstance
{
  char watchdog_monitor_init_IgnoreBool;
  char watchdog_monitor_init_CallbackBool;
  CMOCK_watchdog_monitor_init_CALLBACK watchdog_monitor_init_CallbackFunctionPointer;
  int watchdog_monitor_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE watchdog_monitor_init_CallInstance;
  char watchdog_register_task_IgnoreBool;
  int watchdog_register_task_FinalReturn;
  char watchdog_register_task_CallbackBool;
  CMOCK_watchdog_register_task_CALLBACK watchdog_register_task_CallbackFunctionPointer;
  int watchdog_register_task_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE watchdog_register_task_CallInstance;
  char watchdog_task_create_IgnoreBool;
  osThreadId_t watchdog_task_create_FinalReturn;
  char watchdog_task_create_CallbackBool;
  CMOCK_watchdog_task_create_CALLBACK watchdog_task_create_CallbackFunctionPointer;
  int watchdog_task_create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE watchdog_task_create_CallInstance;
  char watchdog_alive_IgnoreBool;
  char watchdog_alive_CallbackBool;
  CMOCK_watchdog_alive_CALLBACK watchdog_alive_CallbackFunctionPointer;
  int watchdog_alive_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE watchdog_alive_CallInstance;
  char watchdog_alive_self_IgnoreBool;
  char watchdog_alive_self_CallbackBool;
  CMOCK_watchdog_alive_self_CALLBACK watchdog_alive_self_CallbackFunctionPointer;
  int watchdog_alive_self_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE watchdog_alive_self_CallInstance;
} Mock;


void mock_watchdog_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.watchdog_monitor_init_CallInstance;
  if (Mock.watchdog_monitor_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_monitor_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.watchdog_monitor_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.watchdog_register_task_CallInstance;
  if (Mock.watchdog_register_task_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_register_task);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.watchdog_register_task_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.watchdog_task_create_CallInstance;
  if (Mock.watchdog_task_create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_task_create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.watchdog_task_create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.watchdog_alive_CallInstance;
  if (Mock.watchdog_alive_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_alive);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.watchdog_alive_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.watchdog_alive_self_CallInstance;
  if (Mock.watchdog_alive_self_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_alive_self);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.watchdog_alive_self_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_watchdog_Init(void)
{
  mock_watchdog_Destroy();
}

void mock_watchdog_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void watchdog_monitor_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_watchdog_monitor_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_watchdog_monitor_init);
  cmock_call_instance = (CMOCK_watchdog_monitor_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.watchdog_monitor_init_CallInstance);
  Mock.watchdog_monitor_init_CallInstance = CMock_Guts_MemNext(Mock.watchdog_monitor_init_CallInstance);
  if (Mock.watchdog_monitor_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.watchdog_monitor_init_CallbackBool &&
      Mock.watchdog_monitor_init_CallbackFunctionPointer != NULL)
  {
    Mock.watchdog_monitor_init_CallbackFunctionPointer(Mock.watchdog_monitor_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.watchdog_monitor_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_monitor_init);
    Mock.watchdog_monitor_init_CallbackFunctionPointer(Mock.watchdog_monitor_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void watchdog_monitor_init_CMockIgnore(void)
{
  Mock.watchdog_monitor_init_IgnoreBool = (char)1;
}

void watchdog_monitor_init_CMockStopIgnore(void)
{
  Mock.watchdog_monitor_init_IgnoreBool = (char)0;
}

void watchdog_monitor_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_monitor_init_CALL_INSTANCE));
  CMOCK_watchdog_monitor_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_monitor_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_monitor_init_CallInstance = CMock_Guts_MemChain(Mock.watchdog_monitor_init_CallInstance, cmock_guts_index);
  Mock.watchdog_monitor_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void watchdog_monitor_init_AddCallback(CMOCK_watchdog_monitor_init_CALLBACK Callback)
{
  Mock.watchdog_monitor_init_IgnoreBool = (char)0;
  Mock.watchdog_monitor_init_CallbackBool = (char)1;
  Mock.watchdog_monitor_init_CallbackCalls = 0;
  Mock.watchdog_monitor_init_CallbackFunctionPointer = Callback;
}

int watchdog_monitor_init_CallCount(void)
{
  return Mock.watchdog_monitor_init_CallbackCalls;
}

void watchdog_monitor_init_Stub(CMOCK_watchdog_monitor_init_CALLBACK Callback)
{
  Mock.watchdog_monitor_init_IgnoreBool = (char)0;
  Mock.watchdog_monitor_init_CallbackBool = (char)0;
  Mock.watchdog_monitor_init_CallbackCalls = 0;
  Mock.watchdog_monitor_init_CallbackFunctionPointer = Callback;
}

int watchdog_register_task(osThreadId_t handle, uint32_t expected_period_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_watchdog_register_task);
  cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.watchdog_register_task_CallInstance);
  Mock.watchdog_register_task_CallInstance = CMock_Guts_MemNext(Mock.watchdog_register_task_CallInstance);
  if (Mock.watchdog_register_task_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.watchdog_register_task_FinalReturn;
    Mock.watchdog_register_task_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.watchdog_register_task_CallbackBool &&
      Mock.watchdog_register_task_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.watchdog_register_task_CallbackFunctionPointer(handle, expected_period_ms, Mock.watchdog_register_task_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_handle)
  {
    UNITY_SET_DETAILS(CMockString_watchdog_register_task,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(osThreadId_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_expected_period_ms)
  {
    UNITY_SET_DETAILS(CMockString_watchdog_register_task,CMockString_expected_period_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_expected_period_ms, expected_period_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.watchdog_register_task_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_register_task);
    cmock_call_instance->ReturnVal = Mock.watchdog_register_task_CallbackFunctionPointer(handle, expected_period_ms, Mock.watchdog_register_task_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_watchdog_register_task(CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance, osThreadId_t handle, uint32_t expected_period_ms);
void CMockExpectParameters_watchdog_register_task(CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance, osThreadId_t handle, uint32_t expected_period_ms)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(osThreadId_t[sizeof(handle) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_handle = 0;
  cmock_call_instance->Expected_expected_period_ms = expected_period_ms;
  cmock_call_instance->IgnoreArg_expected_period_ms = 0;
}

void watchdog_register_task_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_register_task_CALL_INSTANCE));
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_register_task_CallInstance = CMock_Guts_MemChain(Mock.watchdog_register_task_CallInstance, cmock_guts_index);
  Mock.watchdog_register_task_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.watchdog_register_task_IgnoreBool = (char)1;
}

void watchdog_register_task_CMockStopIgnore(void)
{
  if(Mock.watchdog_register_task_IgnoreBool)
    Mock.watchdog_register_task_CallInstance = CMock_Guts_MemNext(Mock.watchdog_register_task_CallInstance);
  Mock.watchdog_register_task_IgnoreBool = (char)0;
}

void watchdog_register_task_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_register_task_CALL_INSTANCE));
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_register_task_CallInstance = CMock_Guts_MemChain(Mock.watchdog_register_task_CallInstance, cmock_guts_index);
  Mock.watchdog_register_task_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void watchdog_register_task_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t handle, uint32_t expected_period_ms, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_register_task_CALL_INSTANCE));
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_register_task_CallInstance = CMock_Guts_MemChain(Mock.watchdog_register_task_CallInstance, cmock_guts_index);
  Mock.watchdog_register_task_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_watchdog_register_task(cmock_call_instance, handle, expected_period_ms);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void watchdog_register_task_AddCallback(CMOCK_watchdog_register_task_CALLBACK Callback)
{
  Mock.watchdog_register_task_IgnoreBool = (char)0;
  Mock.watchdog_register_task_CallbackBool = (char)1;
  Mock.watchdog_register_task_CallbackCalls = 0;
  Mock.watchdog_register_task_CallbackFunctionPointer = Callback;
}

int watchdog_register_task_CallCount(void)
{
  return Mock.watchdog_register_task_CallbackCalls;
}

void watchdog_register_task_Stub(CMOCK_watchdog_register_task_CALLBACK Callback)
{
  Mock.watchdog_register_task_IgnoreBool = (char)0;
  Mock.watchdog_register_task_CallbackBool = (char)0;
  Mock.watchdog_register_task_CallbackCalls = 0;
  Mock.watchdog_register_task_CallbackFunctionPointer = Callback;
}

void watchdog_register_task_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.watchdog_register_task_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handle = 1;
}

void watchdog_register_task_CMockIgnoreArg_expected_period_ms(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_watchdog_register_task_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_register_task_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.watchdog_register_task_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_expected_period_ms = 1;
}

osThreadId_t watchdog_task_create(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_watchdog_task_create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_watchdog_task_create);
  cmock_call_instance = (CMOCK_watchdog_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.watchdog_task_create_CallInstance);
  Mock.watchdog_task_create_CallInstance = CMock_Guts_MemNext(Mock.watchdog_task_create_CallInstance);
  if (Mock.watchdog_task_create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.watchdog_task_create_FinalReturn;
    memcpy((void*)(&Mock.watchdog_task_create_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(osThreadId_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.watchdog_task_create_CallbackBool &&
      Mock.watchdog_task_create_CallbackFunctionPointer != NULL)
  {
    osThreadId_t cmock_cb_ret = Mock.watchdog_task_create_CallbackFunctionPointer(Mock.watchdog_task_create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.watchdog_task_create_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_task_create);
    cmock_call_instance->ReturnVal = Mock.watchdog_task_create_CallbackFunctionPointer(Mock.watchdog_task_create_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void watchdog_task_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_task_create_CALL_INSTANCE));
  CMOCK_watchdog_task_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_task_create_CallInstance = CMock_Guts_MemChain(Mock.watchdog_task_create_CallInstance, cmock_guts_index);
  Mock.watchdog_task_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.watchdog_task_create_IgnoreBool = (char)1;
}

void watchdog_task_create_CMockStopIgnore(void)
{
  if(Mock.watchdog_task_create_IgnoreBool)
    Mock.watchdog_task_create_CallInstance = CMock_Guts_MemNext(Mock.watchdog_task_create_CallInstance);
  Mock.watchdog_task_create_IgnoreBool = (char)0;
}

void watchdog_task_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_task_create_CALL_INSTANCE));
  CMOCK_watchdog_task_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_task_create_CallInstance = CMock_Guts_MemChain(Mock.watchdog_task_create_CallInstance, cmock_guts_index);
  Mock.watchdog_task_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(osThreadId_t[sizeof(cmock_to_return) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
}

void watchdog_task_create_AddCallback(CMOCK_watchdog_task_create_CALLBACK Callback)
{
  Mock.watchdog_task_create_IgnoreBool = (char)0;
  Mock.watchdog_task_create_CallbackBool = (char)1;
  Mock.watchdog_task_create_CallbackCalls = 0;
  Mock.watchdog_task_create_CallbackFunctionPointer = Callback;
}

int watchdog_task_create_CallCount(void)
{
  return Mock.watchdog_task_create_CallbackCalls;
}

void watchdog_task_create_Stub(CMOCK_watchdog_task_create_CALLBACK Callback)
{
  Mock.watchdog_task_create_IgnoreBool = (char)0;
  Mock.watchdog_task_create_CallbackBool = (char)0;
  Mock.watchdog_task_create_CallbackCalls = 0;
  Mock.watchdog_task_create_CallbackFunctionPointer = Callback;
}

void watchdog_alive(osThreadId_t handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_watchdog_alive);
  cmock_call_instance = (CMOCK_watchdog_alive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.watchdog_alive_CallInstance);
  Mock.watchdog_alive_CallInstance = CMock_Guts_MemNext(Mock.watchdog_alive_CallInstance);
  if (Mock.watchdog_alive_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.watchdog_alive_CallbackBool &&
      Mock.watchdog_alive_CallbackFunctionPointer != NULL)
  {
    Mock.watchdog_alive_CallbackFunctionPointer(handle, Mock.watchdog_alive_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_handle)
  {
    UNITY_SET_DETAILS(CMockString_watchdog_alive,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_handle, &handle, sizeof(osThreadId_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.watchdog_alive_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_alive);
    Mock.watchdog_alive_CallbackFunctionPointer(handle, Mock.watchdog_alive_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_watchdog_alive(CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance, osThreadId_t handle);
void CMockExpectParameters_watchdog_alive(CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance, osThreadId_t handle)
{
  memcpy((void*)(&cmock_call_instance->Expected_handle), (const void*)(&handle),
         sizeof(osThreadId_t[sizeof(handle) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_handle = 0;
}

void watchdog_alive_CMockIgnore(void)
{
  Mock.watchdog_alive_IgnoreBool = (char)1;
}

void watchdog_alive_CMockStopIgnore(void)
{
  Mock.watchdog_alive_IgnoreBool = (char)0;
}

void watchdog_alive_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_alive_CALL_INSTANCE));
  CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_alive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_alive_CallInstance = CMock_Guts_MemChain(Mock.watchdog_alive_CallInstance, cmock_guts_index);
  Mock.watchdog_alive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void watchdog_alive_CMockExpect(UNITY_LINE_TYPE cmock_line, osThreadId_t handle)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_alive_CALL_INSTANCE));
  CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_alive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_alive_CallInstance = CMock_Guts_MemChain(Mock.watchdog_alive_CallInstance, cmock_guts_index);
  Mock.watchdog_alive_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_watchdog_alive(cmock_call_instance, handle);
}

void watchdog_alive_AddCallback(CMOCK_watchdog_alive_CALLBACK Callback)
{
  Mock.watchdog_alive_IgnoreBool = (char)0;
  Mock.watchdog_alive_CallbackBool = (char)1;
  Mock.watchdog_alive_CallbackCalls = 0;
  Mock.watchdog_alive_CallbackFunctionPointer = Callback;
}

int watchdog_alive_CallCount(void)
{
  return Mock.watchdog_alive_CallbackCalls;
}

void watchdog_alive_Stub(CMOCK_watchdog_alive_CALLBACK Callback)
{
  Mock.watchdog_alive_IgnoreBool = (char)0;
  Mock.watchdog_alive_CallbackBool = (char)0;
  Mock.watchdog_alive_CallbackCalls = 0;
  Mock.watchdog_alive_CallbackFunctionPointer = Callback;
}

void watchdog_alive_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_watchdog_alive_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_alive_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.watchdog_alive_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handle = 1;
}

void watchdog_alive_self(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_watchdog_alive_self_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_watchdog_alive_self);
  cmock_call_instance = (CMOCK_watchdog_alive_self_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.watchdog_alive_self_CallInstance);
  Mock.watchdog_alive_self_CallInstance = CMock_Guts_MemNext(Mock.watchdog_alive_self_CallInstance);
  if (Mock.watchdog_alive_self_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.watchdog_alive_self_CallbackBool &&
      Mock.watchdog_alive_self_CallbackFunctionPointer != NULL)
  {
    Mock.watchdog_alive_self_CallbackFunctionPointer(Mock.watchdog_alive_self_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.watchdog_alive_self_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_watchdog_alive_self);
    Mock.watchdog_alive_self_CallbackFunctionPointer(Mock.watchdog_alive_self_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void watchdog_alive_self_CMockIgnore(void)
{
  Mock.watchdog_alive_self_IgnoreBool = (char)1;
}

void watchdog_alive_self_CMockStopIgnore(void)
{
  Mock.watchdog_alive_self_IgnoreBool = (char)0;
}

void watchdog_alive_self_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_watchdog_alive_self_CALL_INSTANCE));
  CMOCK_watchdog_alive_self_CALL_INSTANCE* cmock_call_instance = (CMOCK_watchdog_alive_self_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.watchdog_alive_self_CallInstance = CMock_Guts_MemChain(Mock.watchdog_alive_self_CallInstance, cmock_guts_index);
  Mock.watchdog_alive_self_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void watchdog_alive_self_AddCallback(CMOCK_watchdog_alive_self_CALLBACK Callback)
{
  Mock.watchdog_alive_self_IgnoreBool = (char)0;
  Mock.watchdog_alive_self_CallbackBool = (char)1;
  Mock.watchdog_alive_self_CallbackCalls = 0;
  Mock.watchdog_alive_self_CallbackFunctionPointer = Callback;
}

int watchdog_alive_self_CallCount(void)
{
  return Mock.watchdog_alive_self_CallbackCalls;
}

void watchdog_alive_self_Stub(CMOCK_watchdog_alive_self_CALLBACK Callback)
{
  Mock.watchdog_alive_self_IgnoreBool = (char)0;
  Mock.watchdog_alive_self_CallbackBool = (char)0;
  Mock.watchdog_alive_self_CallbackCalls = 0;
  Mock.watchdog_alive_self_CallbackFunctionPointer = Callback;
}

