/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MAIN_H
#define _MOCK_MAIN_H

#include "unity.h"
#include "main.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_main_Init(void);
void mock_main_Destroy(void);
void mock_main_Verify(void);




#define NVIC_SystemReset_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("NVIC_SystemReset requires _Ignore (not AndReturn)");
#define NVIC_SystemReset_Ignore() NVIC_SystemReset_CMockIgnore()
void NVIC_SystemReset_CMockIgnore(void);
#define NVIC_SystemReset_StopIgnore() NVIC_SystemReset_CMockStopIgnore()
void NVIC_SystemReset_CMockStopIgnore(void);
#define NVIC_SystemReset_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("NVIC_SystemReset requires _Expect (not AndReturn)");
#define NVIC_SystemReset_Expect() NVIC_SystemReset_CMockExpect(__LINE__)
void NVIC_SystemReset_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_NVIC_SystemReset_CALLBACK)(int cmock_num_calls);
void NVIC_SystemReset_AddCallback(CMOCK_NVIC_SystemReset_CALLBACK Callback);
void NVIC_SystemReset_Stub(CMOCK_NVIC_SystemReset_CALLBACK Callback);
#define NVIC_SystemReset_StubWithCallback NVIC_SystemReset_Stub
int NVIC_SystemReset_CallCount(void);
#define Error_Handler_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Error_Handler requires _Ignore (not AndReturn)");
#define Error_Handler_Ignore() Error_Handler_CMockIgnore()
void Error_Handler_CMockIgnore(void);
#define Error_Handler_StopIgnore() Error_Handler_CMockStopIgnore()
void Error_Handler_CMockStopIgnore(void);
#define Error_Handler_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Error_Handler requires _Expect (not AndReturn)");
#define Error_Handler_Expect() Error_Handler_CMockExpect(__LINE__)
void Error_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Error_Handler_CALLBACK)(int cmock_num_calls);
void Error_Handler_AddCallback(CMOCK_Error_Handler_CALLBACK Callback);
void Error_Handler_Stub(CMOCK_Error_Handler_CALLBACK Callback);
#define Error_Handler_StubWithCallback Error_Handler_Stub
int Error_Handler_CallCount(void);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
