/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_state_machine.h"

static const char* CMockString_interval_ms = "interval_ms";
static const char* CMockString_state_machine_get_beacon_interval = "state_machine_get_beacon_interval";
static const char* CMockString_state_machine_get_state = "state_machine_get_state";
static const char* CMockString_state_machine_init = "state_machine_init";
static const char* CMockString_state_machine_request_transition = "state_machine_request_transition";
static const char* CMockString_state_machine_set_beacon_interval = "state_machine_set_beacon_interval";
static const char* CMockString_state_machine_task_create = "state_machine_task_create";
static const char* CMockString_target = "target";
static const char* CMockString_trigger = "trigger";

typedef struct _CMOCK_state_machine_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_state_machine_init_CALL_INSTANCE;

typedef struct _CMOCK_state_machine_task_create_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  osThreadId_t ReturnVal;

} CMOCK_state_machine_task_create_CALL_INSTANCE;

typedef struct _CMOCK_state_machine_get_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  obw_state_t ReturnVal;

} CMOCK_state_machine_get_state_CALL_INSTANCE;

typedef struct _CMOCK_state_machine_request_transition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  obw_state_t Expected_target;
  uint8_t Expected_trigger;
  char IgnoreArg_target;
  char IgnoreArg_trigger;

} CMOCK_state_machine_request_transition_CALL_INSTANCE;

typedef struct _CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE;

typedef struct _CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t Expected_interval_ms;
  char IgnoreArg_interval_ms;

} CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE;

static struct mock_state_machineInstance
{
  char state_machine_init_IgnoreBool;
  char state_machine_init_CallbackBool;
  CMOCK_state_machine_init_CALLBACK state_machine_init_CallbackFunctionPointer;
  int state_machine_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_init_CallInstance;
  char state_machine_task_create_IgnoreBool;
  osThreadId_t state_machine_task_create_FinalReturn;
  char state_machine_task_create_CallbackBool;
  CMOCK_state_machine_task_create_CALLBACK state_machine_task_create_CallbackFunctionPointer;
  int state_machine_task_create_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_task_create_CallInstance;
  char state_machine_get_state_IgnoreBool;
  obw_state_t state_machine_get_state_FinalReturn;
  char state_machine_get_state_CallbackBool;
  CMOCK_state_machine_get_state_CALLBACK state_machine_get_state_CallbackFunctionPointer;
  int state_machine_get_state_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_get_state_CallInstance;
  char state_machine_request_transition_IgnoreBool;
  int state_machine_request_transition_FinalReturn;
  char state_machine_request_transition_CallbackBool;
  CMOCK_state_machine_request_transition_CALLBACK state_machine_request_transition_CallbackFunctionPointer;
  int state_machine_request_transition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_request_transition_CallInstance;
  char state_machine_get_beacon_interval_IgnoreBool;
  uint32_t state_machine_get_beacon_interval_FinalReturn;
  char state_machine_get_beacon_interval_CallbackBool;
  CMOCK_state_machine_get_beacon_interval_CALLBACK state_machine_get_beacon_interval_CallbackFunctionPointer;
  int state_machine_get_beacon_interval_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_get_beacon_interval_CallInstance;
  char state_machine_set_beacon_interval_IgnoreBool;
  char state_machine_set_beacon_interval_CallbackBool;
  CMOCK_state_machine_set_beacon_interval_CALLBACK state_machine_set_beacon_interval_CallbackFunctionPointer;
  int state_machine_set_beacon_interval_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE state_machine_set_beacon_interval_CallInstance;
} Mock;


void mock_state_machine_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.state_machine_init_CallInstance;
  if (Mock.state_machine_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.state_machine_task_create_CallInstance;
  if (Mock.state_machine_task_create_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_task_create);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_task_create_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.state_machine_get_state_CallInstance;
  if (Mock.state_machine_get_state_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_get_state);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_get_state_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.state_machine_request_transition_CallInstance;
  if (Mock.state_machine_request_transition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_request_transition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_request_transition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.state_machine_get_beacon_interval_CallInstance;
  if (Mock.state_machine_get_beacon_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_get_beacon_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_get_beacon_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.state_machine_set_beacon_interval_CallInstance;
  if (Mock.state_machine_set_beacon_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_set_beacon_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.state_machine_set_beacon_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_state_machine_Init(void)
{
  mock_state_machine_Destroy();
}

void mock_state_machine_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void state_machine_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_init);
  cmock_call_instance = (CMOCK_state_machine_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_init_CallInstance);
  Mock.state_machine_init_CallInstance = CMock_Guts_MemNext(Mock.state_machine_init_CallInstance);
  if (Mock.state_machine_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.state_machine_init_CallbackBool &&
      Mock.state_machine_init_CallbackFunctionPointer != NULL)
  {
    Mock.state_machine_init_CallbackFunctionPointer(Mock.state_machine_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.state_machine_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_init);
    Mock.state_machine_init_CallbackFunctionPointer(Mock.state_machine_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void state_machine_init_CMockIgnore(void)
{
  Mock.state_machine_init_IgnoreBool = (char)1;
}

void state_machine_init_CMockStopIgnore(void)
{
  Mock.state_machine_init_IgnoreBool = (char)0;
}

void state_machine_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_init_CALL_INSTANCE));
  CMOCK_state_machine_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_init_CallInstance = CMock_Guts_MemChain(Mock.state_machine_init_CallInstance, cmock_guts_index);
  Mock.state_machine_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void state_machine_init_AddCallback(CMOCK_state_machine_init_CALLBACK Callback)
{
  Mock.state_machine_init_IgnoreBool = (char)0;
  Mock.state_machine_init_CallbackBool = (char)1;
  Mock.state_machine_init_CallbackCalls = 0;
  Mock.state_machine_init_CallbackFunctionPointer = Callback;
}

int state_machine_init_CallCount(void)
{
  return Mock.state_machine_init_CallbackCalls;
}

void state_machine_init_Stub(CMOCK_state_machine_init_CALLBACK Callback)
{
  Mock.state_machine_init_IgnoreBool = (char)0;
  Mock.state_machine_init_CallbackBool = (char)0;
  Mock.state_machine_init_CallbackCalls = 0;
  Mock.state_machine_init_CallbackFunctionPointer = Callback;
}

osThreadId_t state_machine_task_create(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_task_create_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_task_create);
  cmock_call_instance = (CMOCK_state_machine_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_task_create_CallInstance);
  Mock.state_machine_task_create_CallInstance = CMock_Guts_MemNext(Mock.state_machine_task_create_CallInstance);
  if (Mock.state_machine_task_create_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.state_machine_task_create_FinalReturn;
    memcpy((void*)(&Mock.state_machine_task_create_FinalReturn), (const void*)(&cmock_call_instance->ReturnVal),
         sizeof(osThreadId_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.state_machine_task_create_CallbackBool &&
      Mock.state_machine_task_create_CallbackFunctionPointer != NULL)
  {
    osThreadId_t cmock_cb_ret = Mock.state_machine_task_create_CallbackFunctionPointer(Mock.state_machine_task_create_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.state_machine_task_create_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_task_create);
    cmock_call_instance->ReturnVal = Mock.state_machine_task_create_CallbackFunctionPointer(Mock.state_machine_task_create_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void state_machine_task_create_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_task_create_CALL_INSTANCE));
  CMOCK_state_machine_task_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_task_create_CallInstance = CMock_Guts_MemChain(Mock.state_machine_task_create_CallInstance, cmock_guts_index);
  Mock.state_machine_task_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.state_machine_task_create_IgnoreBool = (char)1;
}

void state_machine_task_create_CMockStopIgnore(void)
{
  if(Mock.state_machine_task_create_IgnoreBool)
    Mock.state_machine_task_create_CallInstance = CMock_Guts_MemNext(Mock.state_machine_task_create_CallInstance);
  Mock.state_machine_task_create_IgnoreBool = (char)0;
}

void state_machine_task_create_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, osThreadId_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_task_create_CALL_INSTANCE));
  CMOCK_state_machine_task_create_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_task_create_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_task_create_CallInstance = CMock_Guts_MemChain(Mock.state_machine_task_create_CallInstance, cmock_guts_index);
  Mock.state_machine_task_create_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(osThreadId_t[sizeof(cmock_to_return) == sizeof(osThreadId_t) ? 1 : -1])); /* add osThreadId_t to :treat_as_array if this causes an error */
}

void state_machine_task_create_AddCallback(CMOCK_state_machine_task_create_CALLBACK Callback)
{
  Mock.state_machine_task_create_IgnoreBool = (char)0;
  Mock.state_machine_task_create_CallbackBool = (char)1;
  Mock.state_machine_task_create_CallbackCalls = 0;
  Mock.state_machine_task_create_CallbackFunctionPointer = Callback;
}

int state_machine_task_create_CallCount(void)
{
  return Mock.state_machine_task_create_CallbackCalls;
}

void state_machine_task_create_Stub(CMOCK_state_machine_task_create_CALLBACK Callback)
{
  Mock.state_machine_task_create_IgnoreBool = (char)0;
  Mock.state_machine_task_create_CallbackBool = (char)0;
  Mock.state_machine_task_create_CallbackCalls = 0;
  Mock.state_machine_task_create_CallbackFunctionPointer = Callback;
}

obw_state_t state_machine_get_state(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_get_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_get_state);
  cmock_call_instance = (CMOCK_state_machine_get_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_get_state_CallInstance);
  Mock.state_machine_get_state_CallInstance = CMock_Guts_MemNext(Mock.state_machine_get_state_CallInstance);
  if (Mock.state_machine_get_state_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.state_machine_get_state_FinalReturn;
    Mock.state_machine_get_state_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.state_machine_get_state_CallbackBool &&
      Mock.state_machine_get_state_CallbackFunctionPointer != NULL)
  {
    obw_state_t cmock_cb_ret = Mock.state_machine_get_state_CallbackFunctionPointer(Mock.state_machine_get_state_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.state_machine_get_state_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_get_state);
    cmock_call_instance->ReturnVal = Mock.state_machine_get_state_CallbackFunctionPointer(Mock.state_machine_get_state_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void state_machine_get_state_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_get_state_CALL_INSTANCE));
  CMOCK_state_machine_get_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_get_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_get_state_CallInstance = CMock_Guts_MemChain(Mock.state_machine_get_state_CallInstance, cmock_guts_index);
  Mock.state_machine_get_state_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.state_machine_get_state_IgnoreBool = (char)1;
}

void state_machine_get_state_CMockStopIgnore(void)
{
  if(Mock.state_machine_get_state_IgnoreBool)
    Mock.state_machine_get_state_CallInstance = CMock_Guts_MemNext(Mock.state_machine_get_state_CallInstance);
  Mock.state_machine_get_state_IgnoreBool = (char)0;
}

void state_machine_get_state_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_get_state_CALL_INSTANCE));
  CMOCK_state_machine_get_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_get_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_get_state_CallInstance = CMock_Guts_MemChain(Mock.state_machine_get_state_CallInstance, cmock_guts_index);
  Mock.state_machine_get_state_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void state_machine_get_state_AddCallback(CMOCK_state_machine_get_state_CALLBACK Callback)
{
  Mock.state_machine_get_state_IgnoreBool = (char)0;
  Mock.state_machine_get_state_CallbackBool = (char)1;
  Mock.state_machine_get_state_CallbackCalls = 0;
  Mock.state_machine_get_state_CallbackFunctionPointer = Callback;
}

int state_machine_get_state_CallCount(void)
{
  return Mock.state_machine_get_state_CallbackCalls;
}

void state_machine_get_state_Stub(CMOCK_state_machine_get_state_CALLBACK Callback)
{
  Mock.state_machine_get_state_IgnoreBool = (char)0;
  Mock.state_machine_get_state_CallbackBool = (char)0;
  Mock.state_machine_get_state_CallbackCalls = 0;
  Mock.state_machine_get_state_CallbackFunctionPointer = Callback;
}

int state_machine_request_transition(obw_state_t target, uint8_t trigger)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_request_transition);
  cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_request_transition_CallInstance);
  Mock.state_machine_request_transition_CallInstance = CMock_Guts_MemNext(Mock.state_machine_request_transition_CallInstance);
  if (Mock.state_machine_request_transition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.state_machine_request_transition_FinalReturn;
    Mock.state_machine_request_transition_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.state_machine_request_transition_CallbackBool &&
      Mock.state_machine_request_transition_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.state_machine_request_transition_CallbackFunctionPointer(target, trigger, Mock.state_machine_request_transition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_target)
  {
    UNITY_SET_DETAILS(CMockString_state_machine_request_transition,CMockString_target);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_target, target, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_trigger)
  {
    UNITY_SET_DETAILS(CMockString_state_machine_request_transition,CMockString_trigger);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_trigger, trigger, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.state_machine_request_transition_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_request_transition);
    cmock_call_instance->ReturnVal = Mock.state_machine_request_transition_CallbackFunctionPointer(target, trigger, Mock.state_machine_request_transition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_state_machine_request_transition(CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance, obw_state_t target, uint8_t trigger);
void CMockExpectParameters_state_machine_request_transition(CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance, obw_state_t target, uint8_t trigger)
{
  cmock_call_instance->Expected_target = target;
  cmock_call_instance->IgnoreArg_target = 0;
  cmock_call_instance->Expected_trigger = trigger;
  cmock_call_instance->IgnoreArg_trigger = 0;
}

void state_machine_request_transition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_request_transition_CALL_INSTANCE));
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_request_transition_CallInstance = CMock_Guts_MemChain(Mock.state_machine_request_transition_CallInstance, cmock_guts_index);
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.state_machine_request_transition_IgnoreBool = (char)1;
}

void state_machine_request_transition_CMockStopIgnore(void)
{
  if(Mock.state_machine_request_transition_IgnoreBool)
    Mock.state_machine_request_transition_CallInstance = CMock_Guts_MemNext(Mock.state_machine_request_transition_CallInstance);
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
}

void state_machine_request_transition_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_request_transition_CALL_INSTANCE));
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_request_transition_CallInstance = CMock_Guts_MemChain(Mock.state_machine_request_transition_CallInstance, cmock_guts_index);
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void state_machine_request_transition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, obw_state_t target, uint8_t trigger, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_request_transition_CALL_INSTANCE));
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_request_transition_CallInstance = CMock_Guts_MemChain(Mock.state_machine_request_transition_CallInstance, cmock_guts_index);
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_state_machine_request_transition(cmock_call_instance, target, trigger);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void state_machine_request_transition_AddCallback(CMOCK_state_machine_request_transition_CALLBACK Callback)
{
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
  Mock.state_machine_request_transition_CallbackBool = (char)1;
  Mock.state_machine_request_transition_CallbackCalls = 0;
  Mock.state_machine_request_transition_CallbackFunctionPointer = Callback;
}

int state_machine_request_transition_CallCount(void)
{
  return Mock.state_machine_request_transition_CallbackCalls;
}

void state_machine_request_transition_Stub(CMOCK_state_machine_request_transition_CALLBACK Callback)
{
  Mock.state_machine_request_transition_IgnoreBool = (char)0;
  Mock.state_machine_request_transition_CallbackBool = (char)0;
  Mock.state_machine_request_transition_CallbackCalls = 0;
  Mock.state_machine_request_transition_CallbackFunctionPointer = Callback;
}

void state_machine_request_transition_CMockIgnoreArg_target(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.state_machine_request_transition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_target = 1;
}

void state_machine_request_transition_CMockIgnoreArg_trigger(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_state_machine_request_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_request_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.state_machine_request_transition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_trigger = 1;
}

uint32_t state_machine_get_beacon_interval(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_get_beacon_interval);
  cmock_call_instance = (CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_get_beacon_interval_CallInstance);
  Mock.state_machine_get_beacon_interval_CallInstance = CMock_Guts_MemNext(Mock.state_machine_get_beacon_interval_CallInstance);
  if (Mock.state_machine_get_beacon_interval_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.state_machine_get_beacon_interval_FinalReturn;
    Mock.state_machine_get_beacon_interval_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.state_machine_get_beacon_interval_CallbackBool &&
      Mock.state_machine_get_beacon_interval_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.state_machine_get_beacon_interval_CallbackFunctionPointer(Mock.state_machine_get_beacon_interval_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.state_machine_get_beacon_interval_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_get_beacon_interval);
    cmock_call_instance->ReturnVal = Mock.state_machine_get_beacon_interval_CallbackFunctionPointer(Mock.state_machine_get_beacon_interval_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void state_machine_get_beacon_interval_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE));
  CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_get_beacon_interval_CallInstance = CMock_Guts_MemChain(Mock.state_machine_get_beacon_interval_CallInstance, cmock_guts_index);
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)1;
}

void state_machine_get_beacon_interval_CMockStopIgnore(void)
{
  if(Mock.state_machine_get_beacon_interval_IgnoreBool)
    Mock.state_machine_get_beacon_interval_CallInstance = CMock_Guts_MemNext(Mock.state_machine_get_beacon_interval_CallInstance);
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)0;
}

void state_machine_get_beacon_interval_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE));
  CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_get_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_get_beacon_interval_CallInstance = CMock_Guts_MemChain(Mock.state_machine_get_beacon_interval_CallInstance, cmock_guts_index);
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void state_machine_get_beacon_interval_AddCallback(CMOCK_state_machine_get_beacon_interval_CALLBACK Callback)
{
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)0;
  Mock.state_machine_get_beacon_interval_CallbackBool = (char)1;
  Mock.state_machine_get_beacon_interval_CallbackCalls = 0;
  Mock.state_machine_get_beacon_interval_CallbackFunctionPointer = Callback;
}

int state_machine_get_beacon_interval_CallCount(void)
{
  return Mock.state_machine_get_beacon_interval_CallbackCalls;
}

void state_machine_get_beacon_interval_Stub(CMOCK_state_machine_get_beacon_interval_CALLBACK Callback)
{
  Mock.state_machine_get_beacon_interval_IgnoreBool = (char)0;
  Mock.state_machine_get_beacon_interval_CallbackBool = (char)0;
  Mock.state_machine_get_beacon_interval_CallbackCalls = 0;
  Mock.state_machine_get_beacon_interval_CallbackFunctionPointer = Callback;
}

void state_machine_set_beacon_interval(uint32_t interval_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_state_machine_set_beacon_interval);
  cmock_call_instance = (CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.state_machine_set_beacon_interval_CallInstance);
  Mock.state_machine_set_beacon_interval_CallInstance = CMock_Guts_MemNext(Mock.state_machine_set_beacon_interval_CallInstance);
  if (Mock.state_machine_set_beacon_interval_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.state_machine_set_beacon_interval_CallbackBool &&
      Mock.state_machine_set_beacon_interval_CallbackFunctionPointer != NULL)
  {
    Mock.state_machine_set_beacon_interval_CallbackFunctionPointer(interval_ms, Mock.state_machine_set_beacon_interval_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_interval_ms)
  {
    UNITY_SET_DETAILS(CMockString_state_machine_set_beacon_interval,CMockString_interval_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_interval_ms, interval_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.state_machine_set_beacon_interval_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_state_machine_set_beacon_interval);
    Mock.state_machine_set_beacon_interval_CallbackFunctionPointer(interval_ms, Mock.state_machine_set_beacon_interval_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_state_machine_set_beacon_interval(CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance, uint32_t interval_ms);
void CMockExpectParameters_state_machine_set_beacon_interval(CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance, uint32_t interval_ms)
{
  cmock_call_instance->Expected_interval_ms = interval_ms;
  cmock_call_instance->IgnoreArg_interval_ms = 0;
}

void state_machine_set_beacon_interval_CMockIgnore(void)
{
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)1;
}

void state_machine_set_beacon_interval_CMockStopIgnore(void)
{
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)0;
}

void state_machine_set_beacon_interval_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE));
  CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_set_beacon_interval_CallInstance = CMock_Guts_MemChain(Mock.state_machine_set_beacon_interval_CallInstance, cmock_guts_index);
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void state_machine_set_beacon_interval_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t interval_ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE));
  CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.state_machine_set_beacon_interval_CallInstance = CMock_Guts_MemChain(Mock.state_machine_set_beacon_interval_CallInstance, cmock_guts_index);
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_state_machine_set_beacon_interval(cmock_call_instance, interval_ms);
}

void state_machine_set_beacon_interval_AddCallback(CMOCK_state_machine_set_beacon_interval_CALLBACK Callback)
{
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)0;
  Mock.state_machine_set_beacon_interval_CallbackBool = (char)1;
  Mock.state_machine_set_beacon_interval_CallbackCalls = 0;
  Mock.state_machine_set_beacon_interval_CallbackFunctionPointer = Callback;
}

int state_machine_set_beacon_interval_CallCount(void)
{
  return Mock.state_machine_set_beacon_interval_CallbackCalls;
}

void state_machine_set_beacon_interval_Stub(CMOCK_state_machine_set_beacon_interval_CALLBACK Callback)
{
  Mock.state_machine_set_beacon_interval_IgnoreBool = (char)0;
  Mock.state_machine_set_beacon_interval_CallbackBool = (char)0;
  Mock.state_machine_set_beacon_interval_CallbackCalls = 0;
  Mock.state_machine_set_beacon_interval_CallbackFunctionPointer = Callback;
}

void state_machine_set_beacon_interval_CMockIgnoreArg_interval_ms(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_state_machine_set_beacon_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.state_machine_set_beacon_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_interval_ms = 1;
}

